using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace App.Web.Infra.Queries.Accounting.AggregateAnalysis
{
    public class _Class
    {
    }
}
/* AggregateAnalysis
 
SELECT
	A.CODE,
	A.NAME,
    T.TRNDATE,
    T.PERIOD,
    T.LDEBIT,
    T.LCREDIT
FROM 
	ACNT A INNER JOIN 
	ACNTRN T ON T.ACNT = A.ACNT INNER JOIN 
	ACNSCHEMA C ON C.ACNSCHEMA = A.ACNSCHEMA
WHERE
    A.ACNSCHEMA = C.ACNSCHEMA
    AND A.SODTYPE   = 89
	AND A.CODE LIKE '30%'
    AND A.IASACN   IN (0,1)
	AND T.COMPANY   = 1000
	AND T.TRNDATE  >= '20210101'
	AND T.TRNDATE  <  '20220101'
	AND T.ISCANCEL IN (0,2)
	AND T.ISGL     IN (0,1)
	AND T.ISIAS     = 1
	AND T.APPRV     = 1
	AND T.PERIOD   <> 0
 */

/* Schema per Year
 SELECT 
	A.COMPANY AS CompanyId
	,A.FISCPRD AS [Year]
	,A.ACNSCHEMA AS [Schema] 
FROM 
	FISCPRD A 
WHERE 
	A.COMPANY=1000
 */
/* Περίοδοι εταιρείας
 SELECT 
	A.FISCPRD AS [Year]
	,A.PERIOD AS [Period]
	,A.FROMDATE AS FromDate
	,A.FINALDATE AS ToDate
FROM PERIOD A 
WHERE 
	A.COMPANY=1000 and FISCPRD = 2025
ORDER 
	BY A.PERIOD

SELECT A.COMPANY,A.FISCPRD,A.NAME,A.FROMDATE,A.FINALDATE,A.ACNSCHEMA,A.ISACTIVE,A.LOCKFISCPRD,A.INPAYVAT,A.PAYVATTYPE,A.PRORATA,A.PRORATAPRCNT 
FROM FISCPRD A 
WHERE A.COMPANY=1000
 */

/* ACCOUNT CODE BY SCHEMA
 
SELECT 
	B.CODE, B.NAME, B.ACNSCHEMA
    --   A.PERIOD AS Period, 
    --   CAST(A.CREDIT AS DECIMAL(18,2)) AS Debit, 
    --   CAST(A.DEBIT AS DECIMAL(18,2)) AS Credit,
	   --B.ACNSCHEMA
FROM 
	ACNHEADER AS X INNER JOIN
    ACNTRN AS A ON X.ACNEDIT = A.ACNEDIT AND X.ACNEDIT = A.ACNEDIT AND X.ACNHEADER = A.ACNHEADER INNER JOIN
    ACNT B ON A.ACNT = B.ACNT INNER JOIN 
	FISCPRD F ON F.COMPANY = X.COMPANY AND F.FISCPRD = YEAR(X.TRNDATE) 
WHERE 
	X.COMPANY = 1000
	AND (A.CREDIT <> 0 OR A.DEBIT <> 0)
    AND X.SODTYPE = 89
    AND (B.ACNSCHEMA = F.ACNSCHEMA)
GROUP BY B.CODE, B.NAME,B.ACNSCHEMA
ORDER BY B.CODE
 */

/* Πληρωμές Γ'
SELECT 
	T.LLINEVAL, T.TLINEVAL, T.SOPAYTYPE
	,A.COMPANY,A.FINDOC,A.SOSOURCE,A.SOREDIR,A.TRNDATE,A.SERIES,A.FPRMS,A.FINCODE
	,A.SODTYPE,A.TRDR,B.SODTYPE AS X_SODTYPE,B.CODE AS X_CODE,B.NAME AS X_NAME,A.ISPRINT,A.APPRV
	,ISNULL(A.CCCSUMDISC1,0) AS CCCSUMDISC1  
FROM 
	FINDOC A LEFT OUTER JOIN 
	TRDR B ON A.TRDR=B.TRDR LEFT OUTER JOIN 
	TRDFLINES T ON T.FINDOC = A.FINDOC
WHERE 
	A.COMPANY=1000 
	AND A.TRNDATE>='20241201' AND A.TRNDATE<'20250101' 
	AND  (A.ISCANCEL IN (0,2)) AND  ((A.SOSOURCE = 1281) OR (A.SOSOURCE=1681))  AND ((  B.SODTYPE =12  )  OR ( B.SODTYPE = 16  ) ) 
ORDER BY A.SOSOURCE,A.TRNDATE
 */
/* Εισπράξεις Γ'
 SELECT 
	T.LLINEVAL, T.TLINEVAL, T.SOPAYTYPE,
	A.COMPANY,A.FINDOC,A.SOSOURCE,A.SOREDIR,A.TRNDATE,A.SERIES,A.FPRMS,A.FINCODE
	,A.SODTYPE,A.TRDR,B.SODTYPE AS X_SODTYPE,B.CODE AS X_CODE,B.NAME AS X_NAME,A.ISPRINT,A.APPRV
	,ISNULL(A.CCCSUMDISC1,0) AS CCCSUMDISC1  
FROM 
	FINDOC A LEFT OUTER JOIN 
	TRDR B ON A.TRDR=B.TRDR LEFT OUTER JOIN 
	TRDFLINES T ON T.FINDOC = A.FINDOC
WHERE 
	A.COMPANY=1000 
	AND A.TRNDATE>='20240101' AND A.TRNDATE<'20250101' 
	AND  (A.ISCANCEL IN (0,2)) AND  ((A.SOSOURCE = 1381) OR (A.SOSOURCE=1581))  AND ((  B.SODTYPE =13  )  OR ( B.SODTYPE = 15  ) ) 
ORDER BY A.SOSOURCE,A.TRNDATE

 */