namespace App.Web.Infra.Queries.Payroll
{
    public static partial class ApdContributionQuery
    {
		public static string EfkaTeka => @"
			SELECT 
				V.SUM_KRATHSEIS_1 AS EfkaEmployer, V.SUM_KRATHSEIS_2 AS Teka 
				,V.ID_PERIODOS AS Periodos, E.ID_EMP AS EmployeeId, CONCAT(E.SURNAME, ' ', E.NAME) AS FullName
			FROM 
				V_MISTHODOTIKH_KRATHSEIS V LEFT OUTER JOIN 
				PERIODOI_DATA P ON P.ID_PERIODOS =  V.ID_PERIODOS AND P.ID_EMP = V.ID_EMP AND P.XRISI = V.XRISI LEFT OUTER JOIN 
				EMPLOYEE E ON E.ID_EMP = V.ID_EMP LEFT OUTER JOIN 
				CMP C ON C.ID_CMP = P.ID_CMP
			WHERE 
				V.XRISI = @pYear
				--AND V.ID_PERIODOS IN (1,5)
				AND MONTH(P.PERIODOS_DATE) in (@pMonth)
				AND C.ID_CMP = @pCompanyId
		";

        public static string _EfkaTeka => @"SELECT sum(X.SUMEISF1) AS EfkaEmployer, SUM(X.SUMEISF2) AS Teka 
		, X.Periodos AS Periodos, X.ID_EMP AS EmployeeId, CONCAT(X.SURNAME, ' ', X.NAME) AS FullName  

			FROM
				(
				SELECT DISTINCT 
					 EMPLOYEE.AM_IKA 
					 , PERIODOI_DATA.EK_MET 
					 , PERIODOI_DATA.GRADATION1 
					 , GR.DESCR AS GRAD_DESCR
					 --, PERIODOI_DATA.ID_CMP 
					 , dbo.ufn_grkl(CMP.NAME) AS CMPNAME 
					 , PERIODOI_DATA.ID_PERIODOS AS Periodos
					 , PERIODOI_DATA.PERIODOS_DATE
					 , Null as ID_ERGO 
					 , '' AS DESCR_ERGA 
					 , '' AS ALT_DESCR_ERGA 
					 , dbo.ufn_grkl(PERIODOI_DATA.TMHMA) AS TMHMA      
					 , dbo.ufn_grkl(AD.DESCR) AS ADMIN_DESCR           
					 , dbo.ufn_grkl(AD.CODE) AS ADMIN_CODE             
					 , dbo.ufn_grkl(ADS.CODE) AS SUBADMIN_CODE         
					 , dbo.ufn_grkl(ADS.DESCR) AS SUBADMIN_DESCR       
					 , CMP_YPOKAT.COD_YPOKAT ,dbo.ufn_grkl(CMP_YPOKAT.DESCR) as COD_YPOKAT_DESCR
					 ,      PERIODOI_DATA.ID_CMP, dbo.ufn_grkl(EMPLOYEE.SURNAME) AS SURNAME, PERIODOI_DATA.EMP_KIND,

					 PERIODOI_DATA.ID_EMP AS ID_EMP 
					 , EMPLOYEE.SVAT AS VAT 
					 , dbo.ufn_grkl(EMPLOYEE.FTHRNAME) AS FTHRNAME 
					 , dbo.ufn_grkl(EMPLOYEE.NAME) AS NAME 
					 , case when isnull(PERIODOI_DATA.EMP_SPECIAL_TYPE,0) <> 23 THEN dbo.tekmWORKING_DAYS(PERIODOI_DATA.ID_EMP 
					 , PERIODOI_DATA.XRISI 
					 , PERIODOI_DATA.ID_PERIODOS 
					 , PERIODOI_DATA.WORKING_DAYS-CASE WHEN PERIODOI_DATA.CALCTYPE1=2 then dbo.eRound(isnull(V2.GRV_LOXIA_DAYS_NO_ASF,0),0) ELSE IsNull(PERIODOI_DATA.LOXIA_NO_ASF, 0) END ) ELSE 0 END AS  WORKING_DAYS 
					 , CASE WHEN isnull(PERIODOI_DATA.EMP_SPECIAL_TYPE,0) <> 23 THEN PERIODOI_DATA.RWORKING_HOURS ELSE 0 END AS ORES_ERGASIAS 
					 , SUM(CASE WHEN PERIODOI_DATA.ID_PERIODOS= 13 THEN ISNULL(PERIODOI_DATA.CALC_DRATIO,0)            WHEN PERIODOI_DATA.ID_PERIODOS =14 THEN ISNULL(PERIODOI_DATA.CALC_DRATIO,0) + ISNULL(PERIODOI_DATA.CALC_DRATIO_ANASTOLI,0)             WHEN PERIODOI_DATA.ID_PERIODOS IN (15,16,17,22,34,35,36,24,78,79) THEN ISNULL(PERIODOI_DATA.DAYS_GIVEN,0) ELSE 0.0 END) AS DAYS_DORA_EPID      ,  null  as CSC_TOTAL_DAYS 
					 , PERIODOI_DATA.XRISI 
					 , dbo.ufn_grkl(PERIODOI.DESCR) AS DESCR 
					 , dbo.ufn_grkl(PERIODOI_DATA.SPC_DESCR) AS IDIKOTITA 
					 , ISNULL(PERIODOI_DATA.FMY, 0) AS FMY 
					 , ISNULL(PERIODOI_DATA.M_APODOXES, 0) AS  M_APODOXES,                        
					ISNULL(PERIODOI_DATA.PLIROTEO,0) AS PLIROTEO,                             
					ISNULL(PERIODOI_DATA.S_KOSTOS,0) AS S_KOSTOS,                             
					 CASE PERIODOI_DATA.EMP_KIND WHEN 2 THEN PERIODOI_DATA.SALARY_AGREED 
					  ELSE CASE PERIODOI_DATA.MERIKH_APASX WHEN 1 THEN 
						   CASE PERIODOI_DATA.MERIKI_SALARY_AGREED WHEN 0 THEN PERIODOI_DATA.SALARY_AGREED 
							WHEN NULL THEN PERIODOI_DATA.SALARY_AGREED 
							ELSE PERIODOI_DATA.MERIKI_SALARY_AGREED  END 
						 ELSE PERIODOI_DATA.SALARY_AGREED END 
					   END 
					   AS SALARY_AGREED, 
  					 ISNULL(MK.LOIPESAPOD,0) AS LOIPESAPOD,               
					ISNULL(MK.APODPERIODOY,0) AS APODPERIODOY,           
					SUM(ISNULL(MK.LOIPESAPOD,0)+ISNULL(MK.APODPERIODOY,0)) AS SUMAPOD,  
					ISNULL(MK.POSO_ERGOD_2,0) + CASE WHEN ISNULL(PERIODOI_DATA.EMP_CATEGORY,0)=2 THEN ISNULL(MK.POSO_ERGAZ_2,0) ELSE 0 END 
					   +CASE WHEN 0=1 THEN (ISNULL(MK.POSO_ERGOD_TAPIT,0) + CASE WHEN ISNULL(PERIODOI_DATA.EMP_CATEGORY,0)=2 THEN ISNULL(MK.POSO_ERGAZ_TAPIT,0) ELSE 0 END) ELSE 0 END AS POSO_ERGOD_2, 
					ISNULL(MK.POSO_ERGOD_1,0) + CASE WHEN ISNULL(PERIODOI_DATA.EMP_CATEGORY,0)=2 THEN ISNULL(MK.POSO_ERGAZ_1,0) ELSE 0 END  
					   -CASE WHEN 0=1 THEN (ISNULL(MK.POSO_ERGOD_TAPIT,0) + CASE WHEN ISNULL(PERIODOI_DATA.EMP_CATEGORY,0)=2 THEN ISNULL(MK.POSO_ERGAZ_TAPIT,0) ELSE 0 END) ELSE 0 END AS POSO_ERGOD_1, 
					CASE WHEN ISNULL(PERIODOI_DATA.EMP_CATEGORY,0)=2 THEN 0 ELSE ISNULL(MK.POSO_ERGAZ_2,0) END 
					   -ISNULL(MK.POSO_ERGAZ_SYNERGASIA_2,0) 
					   +CASE WHEN 0=1 THEN (CASE WHEN ISNULL(PERIODOI_DATA.EMP_CATEGORY,0)=2 THEN 0 ELSE ISNULL(MK.POSO_ERGAZ_TAPIT,0) END) ELSE 0 END AS POSO_ERGAZ_2, 
					CASE WHEN ISNULL(PERIODOI_DATA.EMP_CATEGORY,0)=2 THEN 0 ELSE ISNULL(MK.POSO_ERGAZ_1,0) END 
					   -ISNULL(MK.POSO_ERGAZ_SYNERGASIA_1,0) 
					   -CASE WHEN 0=1 THEN (CASE WHEN ISNULL(PERIODOI_DATA.EMP_CATEGORY,0)=2 THEN 0 ELSE ISNULL(MK.POSO_ERGAZ_TAPIT,0) END) ELSE 0 END AS POSO_ERGAZ_1, 
					case when periodoi_data.EMP_TYPE = 2 OR (periodoi_data.EMP_TYPE = 9 and periodoi_data.artist_type=10 ) OR (periodoi_data.emp_type = 4 and periodoi_data.EMP_SPECIAL_TYPE in(12,20,21,23) and (isnull(CMP.NOCALC_XARTOSHMO_PLIROTEO,0)=0)) then   
						 SUM(ISNULL(MK.SFMY1,0)+ISNULL(PERIODOI_DATA.FMY,0)) 
					when periodoi_data.emp_type=4 and periodoi_data.emp_special_type=11 then 
						 SUM(ISNULL(MK.SFMY1,0)+ISNULL(PERIODOI_DATA.FMY,0)+IsNull(PERIODOI_DATA.OGA_FMY,0)) 
					else SUM(ISNULL(MK.SFMY1,0)+ISNULL(PERIODOI_DATA.FMY,0)) end AS SUMFMY,                          
					SUM(IsNull(PERIODOI_DATA.FMY_EKT_EISF,0)) as FMY_EKT_EISF, 
					SUM(ISNULL(MK.SUM_KRATHSEIS_1,0) 
					   - CASE WHEN 0=1 THEN (ISNULL(MK.POSO_ERGOD_TAPIT,0)+ISNULL(MK.POSO_ERGAZ_TAPIT,0)) ELSE 0 END ) AS SUMEISF1,  
					SUM(ISNULL(MK.SUM_KRATHSEIS_2,0) 
					   +CASE WHEN 0=1 THEN (ISNULL(MK.POSO_ERGOD_TAPIT,0) +ISNULL(MK.POSO_ERGAZ_TAPIT,0)) ELSE 0 END ) AS SUMEISF2, 
					case when periodoi_data.EMP_TYPE = 2 OR (periodoi_data.EMP_TYPE = 9 and periodoi_data.artist_type=10 ) OR (periodoi_data.emp_type = 4 and periodoi_data.EMP_SPECIAL_TYPE in(12,20,21,23) and (isnull(CMP.NOCALC_XARTOSHMO_PLIROTEO,0)=0)) then   
						 SUM(ISNULL(MK.SFMY1,0)+ISNULL(PERIODOI_DATA.FMY,0)+IsNull(PERIODOI_DATA.FMY_EKT_EISF,0)+ISNULL(MK.POSO_ERGAZ_1,0)+ISNULL(MK.POSO_ERGAZ_2,0)               +IsNull(round(dbo.UFN_XARTOSHMO_VALUE(PERIODOI_DATA.ID_EMP,PERIODOI_DATA.XRISI,PERIODOI_DATA.ID_PERIODOS,0),2),0)) 
					when periodoi_data.emp_type=4 and periodoi_data.emp_special_type=11 then 
						 SUM(ISNULL(MK.SFMY1,0)+ISNULL(PERIODOI_DATA.FMY,0)+ISNULL(MK.POSO_ERGAZ_1,0)+ISNULL(MK.POSO_ERGAZ_2,0)+IsNull(PERIODOI_DATA.OGA_FMY,0)) 
					else SUM(ISNULL(MK.SFMY1,0)+ISNULL(PERIODOI_DATA.FMY,0)+CASE WHEN ISNULL(PERIODOI_DATA.EMP_CATEGORY,0)=2 THEN 0 ELSE ISNULL(MK.POSO_ERGAZ_1,0)+ISNULL(MK.POSO_ERGAZ_2,0) END) + SUM(IsNull(PERIODOI_DATA.FMY_EKT_EISF,0)) end AS SUMKRATISEIS, 
					SUM(ISNULL(PERIODOI_DATA.PLIROTEO,0)+ISNULL(MK.SPLIROTEO1,0)) AS SUMPLIROTEO,                        
					SUM(ISNULL(PERIODOI_DATA.M_APODOXES,0) + ISNULL(MK.POSO_ERGOD_1,0)+ISNULL(MK.POSO_ERGOD_2,0)) AS MIKTESAPODOXES, 
				  case WHEN ISNULL(PERIODOI_DATA.EMP_CATEGORY,0)=2 THEN SUM(ISOP.ISOP_KATHARA)     when (IsNull(periodoi_data.OAED_EPID,0)=1 and IsNull(periodoi_data.OAED_EMP_TYPE,0) in (22,23)) then 0.00     when periodoi_data.EMP_TYPE = 2 and periodoi_data.artist_type=6 then 0.00     when periodoi_data.EMP_TYPE = 2 OR (periodoi_data.EMP_TYPE = 9 and periodoi_data.artist_type=10 ) OR (periodoi_data.emp_type = 4 and periodoi_data.EMP_SPECIAL_TYPE in(12,20,21,23) and (isnull(CMP.NOCALC_XARTOSHMO_PLIROTEO,0)=0)) then   
						 SUM(ISNULL(PERIODOI_DATA.M_APODOXES,0) - ISNULL(MK.SFMY1,0)-IsNull(PERIODOI_DATA.FMY_EKT_EISF,0) - ISNULL(PERIODOI_DATA.FMY,0) - ISNULL(MK.POSO_ERGAZ_1,0) - ISNULL(MK.POSO_ERGAZ_2,0) -IsNull(round(dbo.UFN_XARTOSHMO_VALUE(PERIODOI_DATA.ID_EMP,PERIODOI_DATA.XRISI,PERIODOI_DATA.ID_PERIODOS,0),2),0)) 
					when periodoi_data.emp_type=4 and periodoi_data.emp_special_type=11 then 
						 SUM(ISNULL(PERIODOI_DATA.M_APODOXES,0) - ISNULL(MK.SFMY1,0) - ISNULL(PERIODOI_DATA.FMY,0) - ISNULL(MK.POSO_ERGAZ_1,0) - ISNULL(MK.POSO_ERGAZ_2,0) -IsNull(PERIODOI_DATA.OGA_FMY,0)) 
					else SUM(ISNULL(PERIODOI_DATA.M_APODOXES,0) - ISNULL(MK.SFMY1,0) - ISNULL(PERIODOI_DATA.FMY,0) - ISNULL(MK.POSO_ERGAZ_1,0) - ISNULL(MK.POSO_ERGAZ_2,0) )  - SUM(IsNull(PERIODOI_DATA.FMY_EKT_EISF,0)) end    + SUM(CASE WHEN ((PERIODOI_DATA.EMP_TYPE=9) OR ((PERIODOI_DATA.EMP_TYPE=2) AND (PERIODOI_DATA.ARTIST_KIND=0) AND (PERIODOI_DATA.ARTIST_TYPE=0)))      and not ( (0=1) AND (PERIODOI_DATA.ID_CMP IN (364,365)) AND  (PERIODOI_DATA.EMP_TYPE=9) AND (PERIODOI_DATA.ARTIST_KIND=0) AND (PERIODOI_DATA.GTHORN_CALC_VAT_PLIROTEO=0))  THEN ISNULL(PERIODOI_DATA.VAT_VALUE,0) ELSE 0 END)    +  0    + sum(isnull(MK.KRAT_ERZ_SYN,0))     AS KATHARESAPODOXES, 
					SUM(case WHEN PERIODOI_DATA.EMP_CATEGORY=2 THEN ISNULL(ISOP.ISOP_KATHARA,0) - ISNULL(ISOP.ISOP_POSO_ERGAZ,0) +ISNULL(MK.POSO_ERGAZ_2,0)+ISNULL(MK.POSO_ERGAZ_1,0)              when (not ((periodoi_data.EMP_TYPE = 2 and periodoi_data.artist_type=6) or (IsNull(Periodoi_data.OAED_EPID,0)=1 and IsNull(OAED_EMP_TYPE,0) in (22,23)))) then ISNULL(PERIODOI_DATA.M_APODOXES,0) else 0 end 
						+ ISNULL(MK.POSO_ERGOD_2,0)+ISNULL(MK.POSO_ERGOD_1,0)+isnull(PP.PAROXES_POSO_ERGOD,0))          + (case when periodoi_data.EMP_TYPE = 2 and periodoi_data.artist_type=6 then ISNULL(MK.POSO_ERGAZ_1,0) + ISNULL(MK.POSO_ERGAZ_2,0) else 0 end) /*noOAED*/         + SUM(CASE WHEN ((PERIODOI_DATA.EMP_TYPE=9) OR ((PERIODOI_DATA.EMP_TYPE=2) AND (PERIODOI_DATA.ARTIST_KIND=0) AND (PERIODOI_DATA.ARTIST_TYPE=0)))     and not ( (0=1) AND (PERIODOI_DATA.ID_CMP IN (364,365)) AND  (PERIODOI_DATA.EMP_TYPE=9) AND (PERIODOI_DATA.ARTIST_KIND=0) AND (PERIODOI_DATA.GTHORN_CALC_VAT_PLIROTEO=0))  THEN ISNULL(PERIODOI_DATA.VAT_VALUE,0) ELSE 0 END) 
					   - SUM(CASE WHEN PERIODOI_DATA.EK_MET=1 THEN ISNULL(PERIODOI_DATA.ILL_EPID,0) ELSE 0 END)        - SUM(CASE WHEN PERIODOI_DATA.EK_MET=1 THEN ISNULL(PERIODOI_DATA.ILL_EPID1,0) ELSE 0 END)        - SUM(CASE WHEN PERIODOI_DATA.EK_MET=1 THEN ISNULL(PERIODOI_DATA.LOXIA_EPID,0) ELSE 0 END)        + sum( case when (cmp.NOCALC_XARTOSHMO_PLIROTEO = 1 and isnull(CMP.MELH_DS_XART,0) = 0) AND  (  PERIODOI_DATA.EMP_TYPE in(2,9) OR ( (PERIODOI_DATA.EMP_TYPE = 4) AND (PERIODOI_DATA.EMP_SPECIAL_TYPE in(12,20) ) )) then 
							  dbo.ufn_XARTOSHMO_VALUE(PERIODOI_DATA.ID_EMP,PERIODOI_DATA.XRISI,PERIODOI_DATA.ID_PERIODOS,0) else 0 end ) + sum(isnull(MK.KRAT_ERZ_SYN,0)) AS SINOLIKOKOSTOS  
				,SUM(CASE WHEN ((PERIODOI_DATA.EMP_TYPE=9) OR ((PERIODOI_DATA.EMP_TYPE=2) AND (PERIODOI_DATA.ARTIST_KIND=0) AND (PERIODOI_DATA.ARTIST_TYPE=0))) THEN ISNULL(PERIODOI_DATA.VAT_VALUE,0) ELSE 0 END) as VAT_VALUE 
				,dbo.ufn_grkl(PERIODOI_DATA.REMS) AS REMS  
				,ISNULL(TAMEIO.DESCR,'9999') AS TAMEIO_DESCR ,EMPLOYEE.CODE 
				,SUM(case when periodoi_data.EMP_TYPE = 2 OR (periodoi_data.EMP_TYPE = 9 and periodoi_data.artist_type=10 ) OR (periodoi_data.emp_type = 4 and periodoi_data.EMP_SPECIAL_TYPE in(12,20,21,23) ) then         IsNull(  ROUND(dbo.UFN_XARTOSHMO_VALUE(PERIODOI_DATA.ID_EMP,PERIODOI_DATA.XRISI,PERIODOI_DATA.ID_PERIODOS,0), 2), 0 ) else 0 end) AS XARTOSHMO  
				, SUM(ISNULL(POSO_ERGOD_3,0)) AS POSO_ERGOD_3 
				, SUM(ISNULL(POSO_ERGAZ_3,0)) AS POSO_ERGAZ_3 
				, SUM(ISNULL(KRAT_ika.POSO_ERGOD,0))  AS POSO_ERGOD_ika  , SUM(isnull(KRAT_ika.POSO_ERGAZ, 0)) AS POSO_ERGAZ_ika , SUM(isnull(KRAT_EPIK.POSO_ERGOD, 0)) AS POSO_ERGOD_EPIK  , SUM(isnull(KRAT_EPIK.POSO_ERGAZ, 0)) AS POSO_ERGAZ_EPIK  , cast(null as varchar) TPTE  , cast(null as varchar) TPTE_TEKA  , cast(null as varchar) AMOE  , SUM(ISNULL(MK.POSO_ERGAZ_SYNERGASIA_1,0) + ISNULL(MK.POSO_ERGAZ_SYNERGASIA_2,0)) AS KRAT_ERGAZ_SYNERGASIA  , SUM(case when periodoi_data.EMP_TYPE in (5,10) and isnull(periodoi_data.SSE_WEEK_HOURS_TCHR,0)> 0 then dbo.eRound((periodoi_data.WEEK_HOURS_TCHR/periodoi_data.SSE_WEEK_HOURS_TCHR) * 166.67,2) else 0 end) AS NNT_VAL ,ISNULL(PERIODOI_DATA.TEI_EPIDOTHSH,0) + ISNULL(PERIODOI_DATA.PROKATAVOLI,0) +IsNull((SELECT
				SUM(PERIODOS_PAROXES.POSO) FROM PERIODOS_PAROXES WHERE PERIODOS_PAROXES.ID_EMP = PERIODOI_DATA.ID_EMP 
				AND PERIODOS_PAROXES.XRISI = PERIODOI_DATA.XRISI AND PERIODOS_PAROXES.ID_PERIODOS = PERIODOI_DATA.ID_PERIODOS),0) 
				+ sum(isnull(PERIODOI_DATA.STRIKE_SUM,0)+ISNULL(PERIODOI_DATA.STASI_SUM,0)) AS PROKATAVOLI , CAST(NULL AS FLOAT) AS PAROXI , CAST(NULL AS FLOAT) AS TEI_EPIDOTHSH 
				,ISNULL((SELECT SUM(PERIODOS_PAROXES.POSO_ERGOD) FROM PERIODOS_PAROXES WHERE PERIODOS_PAROXES.ID_EMP = PERIODOI_DATA.ID_EMP  
				AND PERIODOS_PAROXES.XRISI = PERIODOI_DATA.XRISI AND PERIODOS_PAROXES.ID_PERIODOS = PERIODOI_DATA.ID_PERIODOS),0) AS PAROXI_ERD  ,SUM(MK.EPIDOTHSH_OAED) as EPIDOTHSH_OAED  ,sum(dbo.ufn_PLIROTEO(periodoi_data.id_emp, periodoi_data.xrisi, periodoi_data.id_periodos)+0) AS KOSTOSERGOD   ,CAST(NULL AS FLOAT) AS PASENT_POSO  ,cast(null as varchar) AS OD_PROG, cast(null as varchar) DESCR_EP, cast('-999' as varchar) as MIS,0 as ID  FROM     PERIODOI_DATA  
					OUTER APPLY (SELECT * FROM dbo.ufn_GravDays(PERIODOI_DATA.ID_EMP, PERIODOI_DATA.XRISI, PERIODOI_DATA.ID_PERIODOS) WHERE PERIODOI_DATA.CALCTYPE1=2) V2     JOIN (SELECT PD.ID_EMP, PD.OAED_MIS
						  FROM PERIODOI_DATA PD
						  WHERE PD.ID_PERIODOS=0 AND PD.XRISI=0) PDP On PDP.ID_EMP=PERIODOI_DATA.ID_EMP
					LEFT JOIN GRADATIONS GR ON GR.GID = PERIODOI_DATA.GRADATION1
					LEFT JOIN ADMINISTRATION AD ON AD.ID_ADMIN=PERIODOI_DATA.ID_ADMINISTRATION     LEFT JOIN ADMINISTRATION_SUB ADS ON ADS.ID_ADMINS=PERIODOI_DATA.ID_ADMINISTRATION_SUB     LEFT JOIN V_MISTHODOTIKH_KRATHSEIS MK ON PERIODOI_DATA.ID_PERIODOS = MK.ID_PERIODOS 
					AND PERIODOI_DATA.ID_EMP = MK.ID_EMP AND PERIODOI_DATA.XRISI       = MK.XRISI       
					LEFT JOIN (SELECT PA.ID_PERIODOS,PA.XRISI,PA.ID_EMP,MAX(ISNULL(T.DESCR,'')) AS DESCR
							   FROM PERIODOS_APOD PA 
							   JOIN PER_KRATISEIS PK ON PK.ID_PERIODOS_APOD=PA.ID_PERIODOS_APOD 
							   JOIN TAMEIA T ON T.ID_TAMEIO=PK.ID_TAMEIO AND T.IS_BAREA=1 
							   JOIN OM_TAMEIA OT ON OT.ID_TAMEIO=T.ID_TAMEIO AND OT.IS_MAIN=1 
							   GROUP BY  PA.ID_PERIODOS,PA.XRISI,PA.ID_EMP) AS TAMEIO ON TAMEIO.ID_PERIODOS=PERIODOI_DATA.ID_PERIODOS AND TAMEIO.XRISI=PERIODOI_DATA.XRISI AND TAMEIO.ID_EMP=PERIODOI_DATA.ID_EMP
					LEFT JOIN V_PERIODOS_PAROXES PP ON PERIODOI_DATA.ID_EMP = PP.ID_EMP AND PERIODOI_DATA.XRISI  = PP.XRISI AND PERIODOI_DATA.ID_PERIODOS = PP.ID_PERIODOS 
				JOIN CMP_YPOKAT on CMP_YPOKAT.COD_YPOKAT=PERIODOI_DATA.COD_YPOKAT and cmp_ypokat.id_cmp = periodoi_data.id_cmp  
				LEFT JOIN (select SUM(PA.M_APODOXES-IsNull(PA.FMY_SINEK,0)-IsNull(PA.FMY_EKT_EISF_APOD,0)) AS ISOP_KATHARA, /*SUM(IsNull(PK.POSO_ERGAZ,0))*/ 0.00 AS ISOP_POSO_ERGAZ,                   PA.ID_EMP, 
				PA.XRISI, PA.ID_PERIODOS             from PERIODOS_APOD PA             LEFT JOIN (SELECT ID_PERIODOS_APOD, SUM(IsNull(POSO_ERGAZ,0)) as POSO_ERGAZ                        FROM PER_KRATISEIS 
				PK                        GROUP BY ID_PERIODOS_APOD) PK ON PK.ID_PERIODOS_APOD=PA.ID_PERIODOS_APOD             WHERE PA.ID_APODOXHS=11000             GROUP BY PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS) AS ISOP 
				ON ISOP.ID_PERIODOS = PERIODOI_DATA.ID_PERIODOS                                                                         AND ISOP.ID_EMP = 
				PERIODOI_DATA.ID_EMP                                                                                   AND ISOP.XRISI = PERIODOI_DATA.XRISI                     left join (SELECT     
				dbo.PERIODOI_DATA.ID_EMP, dbo.PERIODOI_DATA.XRISI, dbo.PERIODOI_DATA.ID_PERIODOS,  SUM(dbo.PER_KRATISEIS.POSO_ERGAZ)                                AS POSO_ERGAZ, SUM(dbo.PER_KRATISEIS.POSO_ERGOD) AS 
				POSO_ERGOD         FROM          dbo.PER_KRATISEIS JOIN                                dbo.PERIODOS_APOD ON dbo.PERIODOS_APOD.ID_PERIODOS_APOD = dbo.PER_KRATISEIS.ID_PERIODOS_APOD 
				JOIN                                dbo.PERIODOI_DATA ON dbo.PERIODOI_DATA.ID_EMP = dbo.PERIODOS_APOD.ID_EMP AND                                dbo.PERIODOI_DATA.XRISI = dbo.PERIODOS_APOD.XRISI AND 
				dbo.PERIODOI_DATA.ID_PERIODOS = dbo.PERIODOS_APOD.ID_PERIODOS JOIN                                dbo.TAMEIA ON dbo.TAMEIA.ID_TAMEIO = dbo.PER_KRATISEIS.ID_TAMEIO LEFT OUTER 
				JOIN                                dbo.OM_TAMEIA ON dbo.OM_TAMEIA.ID_OMADA = dbo.PERIODOI_DATA.ID_OMADA AND                                dbo.OM_TAMEIA.ID_TAMEIO = dbo.PER_KRATISEIS.ID_TAMEIO         
				WHERE      (dbo.TAMEIA.IS_IKA = 1)         GROUP BY dbo.PERIODOI_DATA.ID_EMP, dbo.PERIODOI_DATA.XRISI, dbo.PERIODOI_DATA.ID_PERIODOS) AS KRAT_IKA ON   KRAT_IKA.ID_EMP = PERIODOI_DATA.ID_EMP AND 
				KRAT_IKA.XRISI = PERIODOI_DATA.XRISI AND   KRAT_IKA.ID_PERIODOS = PERIODOI_DATA.ID_PERIODOS   	left join (SELECT     dbo.PERIODOI_DATA.ID_EMP, dbo.PERIODOI_DATA.XRISI, dbo.PERIODOI_DATA.ID_PERIODOS,  SUM(dbo.PER_KRATISEIS.POSO_ERGAZ)                                 AS POSO_ERGAZ, SUM(dbo.PER_KRATISEIS.POSO_ERGOD) AS POSO_ERGOD            FROM          dbo.PER_KRATISEIS JOIN                                dbo.PERIODOS_APOD ON dbo.PERIODOS_APOD.ID_PERIODOS_APOD = dbo.PER_KRATISEIS.ID_PERIODOS_APOD JOIN                                dbo.PERIODOI_DATA ON dbo.PERIODOI_DATA.ID_EMP = dbo.PERIODOS_APOD.ID_EMP AND                                dbo.PERIODOI_DATA.XRISI = dbo.PERIODOS_APOD.XRISI AND dbo.PERIODOI_DATA.ID_PERIODOS = dbo.PERIODOS_APOD.ID_PERIODOS JOIN                                dbo.TAMEIA ON dbo.TAMEIA.ID_TAMEIO = dbo.PER_KRATISEIS.ID_TAMEIO LEFT OUTER JOIN                                dbo.OM_TAMEIA ON dbo.OM_TAMEIA.ID_OMADA = dbo.PERIODOI_DATA.ID_OMADA AND                                dbo.OM_TAMEIA.ID_TAMEIO = dbo.PER_KRATISEIS.ID_TAMEIO         WHERE    (dbo.TAMEIA.IS_IKA = 0)  AND  dbo.PER_KRATISEIS.ID_TAMEIO NOT in (59,60,61,62,156,179,180,237,239,240,286,327,346,365,366,394							,430,452,453,454,455,456,457,458,459,460,484,485 							,463,464,465,466,467,471,472,473,475,476  							,5036,5037,5038,5039,5046,5050,5051,5052,5054,5055,5137,5292,500,501 							,84,85,88,89,142,143,192,284, 328, 329, 330, 354, 403,404,405,406,407,408,409,410,411,413,414,415,417,418,419 							,420,421,422,423,424,431,516 							,5040,5041,5042,5043,5044,5045,5049,5053,5056,5057,5058,5119,534,535)         GROUP BY dbo.PERIODOI_DATA.ID_EMP, dbo.PERIODOI_DATA.XRISI, dbo.PERIODOI_DATA.ID_PERIODOS) AS KRAT_EPIK ON  KRAT_EPIK.ID_EMP = PERIODOI_DATA.ID_EMP AND KRAT_EPIK.XRISI = PERIODOI_DATA.XRISI AND  KRAT_EPIK.ID_PERIODOS = PERIODOI_DATA.ID_PERIODOS     /*PASENT*/     
					/*OAED*/       
					,PERIODOI,     
					EMPLOYEE,      
					CMP            
				WHERE     PERIODOI_DATA.ID_EMP = EMPLOYEE.ID_EMP 
					AND PERIODOI_DATA.ID_CMP = CMP.ID_CMP  
					AND PERIODOI_DATA.ID_PERIODOS = PERIODOI.ID_PERIODOS 
					AND /*CMP FILTER START*/ PERIODOI_DATA.ID_CMP = @pCompanyId /*CMP FILTER END*/    
					AND PERIODOI_DATA.XRISI in (@pYear) 
					--AND PERIODOI_DATA.PERIODOS_DATE BETWEEN CAST( '2023-4-01' AS datetime) and CAST( '2023-4-30' AS datetime)   
					AND MONTH(PERIODOI_DATA.PERIODOS_DATE) in (@pMonth)
				AND (((PERIODOI_DATA.ID_PERIODOS in (19,21,27,29,37,38,39,49,50,51,52,53,54,55,67,68,69,70,71,72,73,74,75,76,77) OR IsNull(PERIODOI_DATA.M_APODOXES,0)>0 OR isnull(PERIODOI_DATA.M_APODOXES,0) <= 0.001    OR ISNULL(PERIODOI_DATA.DURING_OAED_TOK,0) = 1)       )    ) 
				AND 1=1 AND 1=1 AND 1=1  AND 1=1 AND  (1=1)  AND  (PERIODOI_DATA.EMP_TYPE IS NULL OR (NOT ( (PERIODOI_DATA.EMP_TYPE = 6 ) 
				)))  AND /*CMP FILTER START*/ PERIODOI_DATA.ID_CMP = @pCompanyId /*CMP FILTER END*/  GROUP BY 
					 EMPLOYEE.AM_IKA 
					 , PERIODOI_DATA.ARTIST_TYPE 
					 , PERIODOI_DATA.EMP_TYPE 
					 , PERIODOI_DATA.EMP_SPECIAL_TYPE 
					 , PERIODOI_DATA.ID_CMP 
					 , dbo.ufn_grkl(cmp.name) 
					 , CMP.NOCALC_XARTOSHMO_PLIROTEO 
					 , PERIODOI_DATA.ID_PERIODOS,                         
					PERIODOI_DATA.PERIODOS_DATE,                              
					PERIODOI_DATA.TMHMA,                                      
					AD.DESCR,                                                
					AD.CODE,                                                 
					ADS.CODE,                                                
					ADS.DESCR,                                               
						 PERIODOI_DATA.ID_CMP, dbo.ufn_grkl(EMPLOYEE.SURNAME), PERIODOI_DATA.EMP_KIND,                                     
					PERIODOI_DATA.ID_EMP,                                     
					EMPLOYEE.SVAT,                                            
					PERIODOI_DATA.XRISI,                                      
					EMPLOYEE.FTHRNAME,                                        
					PERIODOI.DESCR,                                           
					PERIODOI_DATA.EK_MET,                                     
					PERIODOI_DATA.GRADATION1,                                 
					GR.DESCR ,                                                
					EMPLOYEE.NAME,                                            
					dbo.tekmWORKING_DAYS(PERIODOI_DATA.ID_EMP, PERIODOI_DATA.XRISI, PERIODOI_DATA.ID_PERIODOS, PERIODOI_DATA.WORKING_DAYS - CASE WHEN PERIODOI_DATA.CALCTYPE1=2 then dbo.eRound(isnull(V2.GRV_LOXIA_DAYS_NO_ASF,0),0) ELSE IsNull(PERIODOI_DATA.LOXIA_NO_ASF, 0) END ) , 
					PERIODOI_DATA.RWORKING_HOURS,
					/*csctotaldaysgrp*/ 
					PERIODOI_DATA.SPC_DESCR ,           
					PERIODOI_DATA.FMY,                  
					PERIODOI_DATA.FMY_EKT_EISF , 
					PERIODOI_DATA.M_APODOXES,           
					PERIODOI_DATA.PLIROTEO,             
					PERIODOI_DATA.S_KOSTOS,             
					PERIODOI_DATA.PROKATAVOLI,          
					PERIODOI_DATA.TEI_EPIDOTHSH,        
					PERIODOI_DATA.MERIKH_APASX,         
  					 PERIODOI_DATA.SALARY_AGREED,        
					PERIODOI_DATA.MERIKI_SALARY_AGREED, 
					CASE WHEN PERIODOI_DATA.MERIKH_APASX = 1 THEN PERIODOI_DATA.MERIKI_SALARY_AGREED ELSE PERIODOI_DATA.SALARY_AGREED END, 
					MK.LOIPESAPOD ,  
					MK.APODPERIODOY, 
					MK.POSO_ERGOD_2, 
					MK.POSO_ERGOD_1, 
					MK.POSO_ERGAZ_2, 
					MK.POSO_ERGAZ_1, 
					MK.POSO_ERGAZ_TAPIT,
					MK.POSO_ERGOD_TAPIT 
				   ,PERIODOI_DATA.EMP_CATEGORY 
				   ,PERIODOI_DATA.OAED_EPID 
				   ,PERIODOI_DATA.OAED_EMP_TYPE 
				   , CMP_YPOKAT.COD_YPOKAT ,CMP_YPOKAT.DESCR 
				   ,PERIODOI_DATA.REMS,EMPLOYEE.CODE,PERIODOI_DATA.EMP_SPECIAL_TYPE 
				   ,MK.POSO_AGAINST ,MK.KRAT_ERZ_SYN  
				   ,MK.POSO_ERGAZ_SYNERGASIA_1,MK.POSO_ERGAZ_SYNERGASIA_2 
				   ,ISNULL(TAMEIO.DESCR,'9999') 
				   ) as X group by X.Periodos, X.ID_EMP , X.SURNAME, X.NAME
				";

        public static string Employers => @" 
			SELECT distinct E.ID_EMP AS EmployeeId
					 , CONCAT(E.SURNAME, ' ', E.NAME) AS FullName
			FROM PERIODOI_DATA AS P LEFT OUTER JOIN
				 EMPLOYEE AS E ON P.ID_EMP = E.ID_EMP
			WHERE P.ID_CMP = @pCompanyId 
				--AND P.ISACTIVE = 1 
				AND P.XRISI = @pYear 
				AND MONTH(P.PERIODOS_DATE) = @pMonth";

    }
}
