namespace App.Web.Infra.Queries.Payroll
{
    public static partial class ApdTekaQuery
    {
        public static string PayrollEmployees => @"			
			SELECT DISTINCT
				X.ID_EMP AS EmployeeId
				--, x.XRISI AS [Year]
				--, x.ID_PERIODOS AS [Period]
				, X.SURNAME + ' ' + X.EMPNAME AS EmployeeName
			FROM (
			SELECT DISTINCT 
				PATINDEX('%[^0-9]%', RTRIM(LTRIM(EMPLOYEE.CODE))) AS Expr1, REPLICATE(0, 50 - LEN(EMPLOYEE.CODE)) + EMPLOYEE.CODE AS Expr2, LEN(EMPLOYEE.CODE) AS Expr3, EMPLOYEE.CODE, dbo.ufn_grkl(EMPLOYEE.SURNAME) 
				AS SURNAME, dbo.ufn_grkl(EMPLOYEE.NAME) AS EMPNAME, PERIODOI_DATA.XRISI, PERIODOI_DATA.ID_PERIODOS, PERIODOI_DATA.ID_EMP, PERIODOI_DATA.ID_CMP, CASE WHEN EMPLOYEE.FRDATE IS NOT NULL 
				THEN CASE WHEN YEAR(PERIODOI_DATA.PERIODOS_DATE) <= YEAR(EMPLOYEE.FRDATE) AND MONTH(PERIODOI_DATA.PERIODOS_DATE) <= MONTH(EMPLOYEE.FRDATE) AND 
				EMPLOYEE.FR_REASON = 9 THEN 1 ELSE PERIODOI_DATA.ISACTIVE END ELSE PERIODOI_DATA.ISACTIVE END AS ISACTIVE, dbo.ufn_grkl(CMP.NAME) AS NAME, 
				dbo.ufn_grkl((CASE periodoi_data.emp_kind WHEN 0 THEN 'ΕΜΜΙΣΘΟΣ' WHEN 1 THEN 'ΗΜΕΡΟΜΙΣΘΙΟΣ' ELSE 'ΩΡΟΜΙΣΘΙΟΣ' END)) AS EMP_KIND1, dbo.ufn_grkl(PERIODOI.DESCR) AS DESCR, PERIODOI_DATA.COD_YPOKAT, 
				dbo.ufn_grkl(VPD.REMS) AS REMS, ISNULL(VPD.ID_APOZ, 0) AS ID_APOZ, CMP.CMP_TYPE, EMPLOYEE.VAT, EMPLOYEE.SVAT, VESP.EMP_SPECIAL_TYPE_DESCR, 
			CASE WHEN PERIODOI_DATA.MERIKH_APASX = 1 THEN 'ΝΑΙ' ELSE 'ΟΧΙ' END AS MERIKH_APASX_DESCR
			FROM     
				CMP INNER JOIN
				PERIODOI_DATA ON CMP.ID_CMP = PERIODOI_DATA.ID_CMP INNER JOIN
				EMPLOYEE ON PERIODOI_DATA.ID_EMP = EMPLOYEE.ID_EMP INNER JOIN
				PERIODOI ON PERIODOI_DATA.ID_PERIODOS = PERIODOI.ID_PERIODOS LEFT OUTER JOIN
				V_EMP_SPECIAL_TYPE AS VESP ON VESP.ID_EMP_SPECIAL_TYPE = PERIODOI_DATA.EMP_SPECIAL_TYPE AND PERIODOI_DATA.EMP_TYPE = 4 LEFT OUTER JOIN
				VAD_PERIODOI_DATA AS VPD ON VPD.ID_EMP = PERIODOI_DATA.ID_EMP AND VPD.ID_PERIODOS = PERIODOI_DATA.ID_PERIODOS AND VPD.XRISI = PERIODOI_DATA.XRISI AND 1 = 0
			WHERE  
				(PERIODOI_DATA.XRISI > 0) AND (PERIODOI_DATA.ID_PERIODOS IN (19, 21, 27, 29, 37, 38, 39, 49, 50, 51, 52, 53, 54, 55, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77)) AND (NOT (ISNULL(EMPLOYEE.IS_APDEMP, 0) = 1 AND 
				ISNULL(PERIODOI_DATA.EMP_TYPE, 0) = 1)) AND (PERIODOI_DATA.PERIODOS_DATE BETWEEN @pStartingDate AND @pEndingDate) AND (PERIODOI_DATA.XRISI = @pYear) AND (PERIODOI_DATA.EMP_TYPE IS NULL OR
				NOT (PERIODOI_DATA.EMP_TYPE = 6)) AND (PERIODOI_DATA.ID_CMP IN (@pCompanyId)) OR
				(PERIODOI_DATA.XRISI > 0) AND (NOT (ISNULL(EMPLOYEE.IS_APDEMP, 0) = 1 AND ISNULL(PERIODOI_DATA.EMP_TYPE, 0) = 1)) AND (PERIODOI_DATA.PERIODOS_DATE BETWEEN @pStartingDate AND @pEndingDate) AND 
				(PERIODOI_DATA.XRISI = @pYear) AND (PERIODOI_DATA.EMP_TYPE IS NULL OR
				NOT (PERIODOI_DATA.EMP_TYPE = 6)) AND (PERIODOI_DATA.ID_CMP IN (@pCompanyId)) AND (ISNULL(PERIODOI_DATA.M_APODOXES, 0) > 0) OR
				(PERIODOI_DATA.XRISI > 0) AND (NOT (ISNULL(EMPLOYEE.IS_APDEMP, 0) = 1 AND ISNULL(PERIODOI_DATA.EMP_TYPE, 0) = 1)) AND (PERIODOI_DATA.PERIODOS_DATE BETWEEN @pStartingDate AND @pEndingDate) AND 
				(PERIODOI_DATA.XRISI = @pYear) AND (PERIODOI_DATA.EMP_TYPE IS NULL OR
				NOT (PERIODOI_DATA.EMP_TYPE = 6)) AND (PERIODOI_DATA.ID_CMP IN (@pCompanyId)) AND (ISNULL(PERIODOI_DATA.M_APODOXES, 0) <= 0.001) OR
				(PERIODOI_DATA.XRISI > 0) AND (NOT (ISNULL(EMPLOYEE.IS_APDEMP, 0) = 1 AND ISNULL(PERIODOI_DATA.EMP_TYPE, 0) = 1)) AND (PERIODOI_DATA.PERIODOS_DATE BETWEEN @pStartingDate AND @pEndingDate) AND 
				(PERIODOI_DATA.XRISI = @pYear) AND (PERIODOI_DATA.EMP_TYPE IS NULL OR
				NOT (PERIODOI_DATA.EMP_TYPE = 6)) AND (PERIODOI_DATA.ID_CMP IN (@pCompanyId)) AND (ISNULL(PERIODOI_DATA.DURING_OAED_TOK, 0) = 1)
			--ORDER BY 
			--	NAME, PERIODOI_DATA.ID_CMP, PERIODOI_DATA.ID_PERIODOS, Expr1, Expr2, Expr3
			) AS X
			WHERE 
				(X.ID_PERIODOS BETWEEN 1 AND 12 AND X.ID_PERIODOS = MONTH(@pStartingDate)) OR X.ID_PERIODOS > 12
        ";
        public static string Employees => @"
			DECLARE @StartOfMonth date = DATEFROMPARTS(@pYear, @pPeriod, 1);
			DECLARE @EndOfMonth   date = EOMONTH(@StartOfMonth);

			SELECT 
				  V.ID_EMP AS EmployeeId
				, @pYear   AS [Year]
				, @pPeriod AS [Period]
				, V.SURNAME + ' ' + V.NAME AS EmployeeName
			FROM 
				dbo.vpr_WRKListFull(@pYear,'admin',@pCompanyId,'*',0,0) AS V
			WHERE 
				V.HRDATE <= @EndOfMonth   
				AND (V.FRDATE IS NULL OR V.FRDATE >= @StartOfMonth);
        ";
		public static string PayrollStatus => @"
			SELECT DISTINCT
				   EMPLOYEE.AM_IKA,
				   PERIODOI_DATA.EK_MET,
				   PERIODOI_DATA.GRADATION1,
				   GR.DESCR AS GRAD_DESCR,
				   PERIODOI_DATA.ID_CMP,
				   dbo.ufn_grkl(CMP.NAME) AS CMPNAME,
				   PERIODOI_DATA.ID_PERIODOS AS PeriodId,
				   PERIODOI_DATA.PERIODOS_DATE,
				   NULL AS ID_ERGO,
				   '' AS DESCR_ERGA,
				   '' AS ALT_DESCR_ERGA,
				   dbo.ufn_grkl(PERIODOI_DATA.TMHMA) AS TMHMA,
				   dbo.ufn_grkl(AD.DESCR) AS ADMIN_DESCR,
				   dbo.ufn_grkl(AD.CODE) AS ADMIN_CODE,
				   dbo.ufn_grkl(ADS.CODE) AS SUBADMIN_CODE,
				   dbo.ufn_grkl(ADS.DESCR) AS SUBADMIN_DESCR,
				   CMP_YPOKAT.COD_YPOKAT,
				   dbo.ufn_grkl(CMP_YPOKAT.DESCR) AS COD_YPOKAT_DESCR,
				   PERIODOI_DATA.ID_CMP,
				   dbo.ufn_grkl(EMPLOYEE.SURNAME) AS SURNAME,
				   PERIODOI_DATA.EMP_KIND,
				   PERIODOI_DATA.ID_EMP AS ID_EMP,
				   EMPLOYEE.SVAT AS VAT,
				   dbo.ufn_grkl(EMPLOYEE.FTHRNAME) AS FTHRNAME,
				   dbo.ufn_grkl(EMPLOYEE.NAME) AS NAME,
				   CASE
					   WHEN ISNULL(PERIODOI_DATA.EMP_SPECIAL_TYPE, 0) <> 23 THEN
						   dbo.tekmWORKING_DAYS(
							   PERIODOI_DATA.ID_EMP,
							   PERIODOI_DATA.XRISI,
							   PERIODOI_DATA.ID_PERIODOS,
							   PERIODOI_DATA.WORKING_DAYS
							   - CASE
									 WHEN PERIODOI_DATA.CALCTYPE1 = 2
										 THEN dbo.eRound(ISNULL(V2.GRV_LOXIA_DAYS_NO_ASF, 0), 0)
									 ELSE ISNULL(PERIODOI_DATA.LOXIA_NO_ASF, 0)
								 END
						   )
					   ELSE 0
				   END AS WORKING_DAYS,
				   CASE
					   WHEN ISNULL(PERIODOI_DATA.EMP_SPECIAL_TYPE, 0) <> 23
						   THEN PERIODOI_DATA.RWORKING_HOURS
					   ELSE 0
				   END AS ORES_ERGASIAS,
				   SUM(
					   CASE
						   WHEN PERIODOI_DATA.ID_PERIODOS = 13
							   THEN ISNULL(PERIODOI_DATA.CALC_DRATIO, 0)
						   WHEN PERIODOI_DATA.ID_PERIODOS = 14
							   THEN ISNULL(PERIODOI_DATA.CALC_DRATIO, 0)
									+ ISNULL(PERIODOI_DATA.CALC_DRATIO_ANASTOLI, 0)
						   WHEN PERIODOI_DATA.ID_PERIODOS IN (15, 16, 17, 22, 34, 35, 36, 24, 78, 79)
							   THEN ISNULL(PERIODOI_DATA.DAYS_GIVEN, 0)
						   ELSE 0.0
					   END
				   ) AS DAYS_DORA_EPID,
				   NULL AS CSC_TOTAL_DAYS,
				   PERIODOI_DATA.XRISI,
				   dbo.ufn_grkl(PERIODOI.DESCR) AS DESCR,
				   dbo.ufn_grkl(PERIODOI_DATA.SPC_DESCR) AS IDIKOTITA,
				   ISNULL(PERIODOI_DATA.FMY, 0) AS FMY,
				   ISNULL(PERIODOI_DATA.M_APODOXES, 0) AS M_APODOXES,
				   ISNULL(PERIODOI_DATA.PLIROTEO, 0) AS PLIROTEO,
				   ISNULL(PERIODOI_DATA.S_KOSTOS, 0) AS S_KOSTOS,
				   CASE PERIODOI_DATA.EMP_KIND
					   WHEN 2 THEN PERIODOI_DATA.SALARY_AGREED
					   ELSE CASE PERIODOI_DATA.MERIKH_APASX
								WHEN 1 THEN
									CASE PERIODOI_DATA.MERIKI_SALARY_AGREED
										WHEN 0    THEN PERIODOI_DATA.SALARY_AGREED
										WHEN NULL THEN PERIODOI_DATA.SALARY_AGREED
										ELSE PERIODOI_DATA.MERIKI_SALARY_AGREED
									END
								ELSE PERIODOI_DATA.SALARY_AGREED
							END
				   END AS SALARY_AGREED,
				   ISNULL(MK.LOIPESAPOD, 0) AS LOIPESAPOD,
				   ISNULL(MK.APODPERIODOY, 0) AS APODPERIODOY,
				   SUM(ISNULL(MK.LOIPESAPOD, 0) + ISNULL(MK.APODPERIODOY, 0)) AS SUMAPOD,
				   ISNULL(MK.POSO_ERGOD_2, 0)
					   + CASE
							 WHEN ISNULL(PERIODOI_DATA.EMP_CATEGORY, 0) = 2
								 THEN ISNULL(MK.POSO_ERGAZ_2, 0)
							 ELSE 0
						 END
					   + CASE
							 WHEN 0 = 1
								 THEN ISNULL(MK.POSO_ERGOD_TAPIT, 0)
									  + CASE
											WHEN ISNULL(PERIODOI_DATA.EMP_CATEGORY, 0) = 2
												THEN ISNULL(MK.POSO_ERGAZ_TAPIT, 0)
											ELSE 0
										END
							 ELSE 0
						 END AS POSO_ERGOD_2,
				   ISNULL(MK.POSO_ERGOD_1, 0)
					   + CASE
							 WHEN ISNULL(PERIODOI_DATA.EMP_CATEGORY, 0) = 2
								 THEN ISNULL(MK.POSO_ERGAZ_1, 0)
							 ELSE 0
						 END
					   - CASE
							 WHEN 0 = 1
								 THEN ISNULL(MK.POSO_ERGOD_TAPIT, 0)
									  + CASE
											WHEN ISNULL(PERIODOI_DATA.EMP_CATEGORY, 0) = 2
												THEN ISNULL(MK.POSO_ERGAZ_TAPIT, 0)
											ELSE 0
										END
							 ELSE 0
						 END AS POSO_ERGOD_1,
				   CASE
					   WHEN ISNULL(PERIODOI_DATA.EMP_CATEGORY, 0) = 2
						   THEN 0
					   ELSE ISNULL(MK.POSO_ERGAZ_2, 0)
				   END
					   - ISNULL(MK.POSO_ERGAZ_SYNERGASIA_2, 0)
					   + CASE
							 WHEN 0 = 1
								 THEN CASE
										  WHEN ISNULL(PERIODOI_DATA.EMP_CATEGORY, 0) = 2
											  THEN 0
										  ELSE ISNULL(MK.POSO_ERGAZ_TAPIT, 0)
									  END
							 ELSE 0
						 END AS POSO_ERGAZ_2,
				   CASE
					   WHEN ISNULL(PERIODOI_DATA.EMP_CATEGORY, 0) = 2
						   THEN 0
					   ELSE ISNULL(MK.POSO_ERGAZ_1, 0)
				   END
					   - ISNULL(MK.POSO_ERGAZ_SYNERGASIA_1, 0)
					   - CASE
							 WHEN 0 = 1
								 THEN CASE
										  WHEN ISNULL(PERIODOI_DATA.EMP_CATEGORY, 0) = 2
											  THEN 0
										  ELSE ISNULL(MK.POSO_ERGAZ_TAPIT, 0)
									  END
							 ELSE 0
						 END AS POSO_ERGAZ_1,
				   CASE
					   WHEN PERIODOI_DATA.EMP_TYPE = 2
							OR (PERIODOI_DATA.EMP_TYPE = 9 AND PERIODOI_DATA.artist_type = 10)
							OR (PERIODOI_DATA.EMP_TYPE = 4
								AND PERIODOI_DATA.EMP_SPECIAL_TYPE IN (12, 20, 21, 23)
								AND ISNULL(CMP.NOCALC_XARTOSHMO_PLIROTEO, 0) = 0)
						   THEN SUM(ISNULL(MK.SFMY1, 0) + ISNULL(PERIODOI_DATA.FMY, 0))
					   WHEN PERIODOI_DATA.EMP_TYPE = 4
							AND PERIODOI_DATA.emp_special_type = 11
						   THEN SUM(ISNULL(MK.SFMY1, 0)
									+ ISNULL(PERIODOI_DATA.FMY, 0)
									+ ISNULL(PERIODOI_DATA.OGA_FMY, 0))
					   ELSE SUM(ISNULL(MK.SFMY1, 0) + ISNULL(PERIODOI_DATA.FMY, 0))
				   END AS SUMFMY,
				   SUM(ISNULL(PERIODOI_DATA.FMY_EKT_EISF, 0)) AS FMY_EKT_EISF,
				   SUM(ISNULL(MK.SUM_KRATHSEIS_1, 0)
					   - CASE
							 WHEN 0 = 1
								 THEN ISNULL(MK.POSO_ERGOD_TAPIT, 0)
									  + ISNULL(MK.POSO_ERGAZ_TAPIT, 0)
							 ELSE 0
						 END) AS Contributions,
				   SUM(ISNULL(MK.SUM_KRATHSEIS_2, 0)
					   + CASE
							 WHEN 0 = 1
								 THEN ISNULL(MK.POSO_ERGOD_TAPIT, 0)
									  + ISNULL(MK.POSO_ERGAZ_TAPIT, 0)
							 ELSE 0
						 END) AS Subsidiary,
				   CASE
					   WHEN PERIODOI_DATA.EMP_TYPE = 2
							OR (PERIODOI_DATA.EMP_TYPE = 9 AND PERIODOI_DATA.artist_type = 10)
							OR (PERIODOI_DATA.EMP_TYPE = 4
								AND PERIODOI_DATA.EMP_SPECIAL_TYPE IN (12, 20, 21, 23)
								AND ISNULL(CMP.NOCALC_XARTOSHMO_PLIROTEO, 0) = 0)
						   THEN SUM(
									ISNULL(MK.SFMY1, 0)
									+ ISNULL(PERIODOI_DATA.FMY, 0)
									+ ISNULL(PERIODOI_DATA.FMY_EKT_EISF, 0)
									+ ISNULL(MK.POSO_ERGAZ_1, 0)
									+ ISNULL(MK.POSO_ERGAZ_2, 0)
									+ ISNULL(
										  ROUND(
											  dbo.UFN_XARTOSHMO_VALUE(
												  PERIODOI_DATA.ID_EMP,
												  PERIODOI_DATA.XRISI,
												  PERIODOI_DATA.ID_PERIODOS,
												  0
											  ),
											  2
										  ),
										  0
									  )
								)
					   WHEN PERIODOI_DATA.EMP_TYPE = 4
							AND PERIODOI_DATA.emp_special_type = 11
						   THEN SUM(
									ISNULL(MK.SFMY1, 0)
									+ ISNULL(PERIODOI_DATA.FMY, 0)
									+ ISNULL(MK.POSO_ERGAZ_1, 0)
									+ ISNULL(MK.POSO_ERGAZ_2, 0)
									+ ISNULL(PERIODOI_DATA.OGA_FMY, 0)
								)
					   ELSE SUM(
								ISNULL(MK.SFMY1, 0)
								+ ISNULL(PERIODOI_DATA.FMY, 0)
								+ CASE
									  WHEN ISNULL(PERIODOI_DATA.EMP_CATEGORY, 0) = 2
										  THEN 0
									  ELSE ISNULL(MK.POSO_ERGAZ_1, 0)
										   + ISNULL(MK.POSO_ERGAZ_2, 0)
								  END
							)
							+ SUM(ISNULL(PERIODOI_DATA.FMY_EKT_EISF, 0))
				   END AS SUMKRATISEIS,
				   SUM(ISNULL(PERIODOI_DATA.PLIROTEO, 0) + ISNULL(MK.SPLIROTEO1, 0)) AS SUMPLIROTEO,
				   SUM(
					   ISNULL(PERIODOI_DATA.M_APODOXES, 0)
					   + ISNULL(MK.POSO_ERGOD_1, 0)
					   + ISNULL(MK.POSO_ERGOD_2, 0)
				   ) AS MIKTESAPODOXES,
				   CASE
					   WHEN ISNULL(PERIODOI_DATA.EMP_CATEGORY, 0) = 2
						   THEN SUM(ISOP.ISOP_KATHARA)
					   WHEN ISNULL(PERIODOI_DATA.OAED_EPID, 0) = 1
							AND ISNULL(PERIODOI_DATA.OAED_EMP_TYPE, 0) IN (22, 23)
						   THEN 0.00
					   WHEN PERIODOI_DATA.EMP_TYPE = 2
							AND PERIODOI_DATA.artist_type = 6
						   THEN 0.00
					   WHEN PERIODOI_DATA.EMP_TYPE = 2
							OR (PERIODOI_DATA.EMP_TYPE = 9 AND PERIODOI_DATA.artist_type = 10)
							OR (PERIODOI_DATA.EMP_TYPE = 4
								AND PERIODOI_DATA.EMP_SPECIAL_TYPE IN (12, 20, 21, 23)
								AND ISNULL(CMP.NOCALC_XARTOSHMO_PLIROTEO, 0) = 0)
						   THEN SUM(
									ISNULL(PERIODOI_DATA.M_APODOXES, 0)
									- ISNULL(MK.SFMY1, 0)
									- ISNULL(PERIODOI_DATA.FMY_EKT_EISF, 0)
									- ISNULL(PERIODOI_DATA.FMY, 0)
									- ISNULL(MK.POSO_ERGAZ_1, 0)
									- ISNULL(MK.POSO_ERGAZ_2, 0)
									- ISNULL(
										  ROUND(
											  dbo.UFN_XARTOSHMO_VALUE(
												  PERIODOI_DATA.ID_EMP,
												  PERIODOI_DATA.XRISI,
												  PERIODOI_DATA.ID_PERIODOS,
												  0
											  ),
											  2
										  ),
										  0
									  )
								)
					   WHEN PERIODOI_DATA.EMP_TYPE = 4
							AND PERIODOI_DATA.emp_special_type = 11
						   THEN SUM(
									ISNULL(PERIODOI_DATA.M_APODOXES, 0)
									- ISNULL(MK.SFMY1, 0)
									- ISNULL(PERIODOI_DATA.FMY, 0)
									- ISNULL(MK.POSO_ERGAZ_1, 0)
									- ISNULL(MK.POSO_ERGAZ_2, 0)
									- ISNULL(PERIODOI_DATA.OGA_FMY, 0)
								)
					   ELSE SUM(
								ISNULL(PERIODOI_DATA.M_APODOXES, 0)
								- ISNULL(MK.SFMY1, 0)
								- ISNULL(PERIODOI_DATA.FMY, 0)
								- ISNULL(MK.POSO_ERGAZ_1, 0)
								- ISNULL(MK.POSO_ERGAZ_2, 0)
							)
							- SUM(ISNULL(PERIODOI_DATA.FMY_EKT_EISF, 0))
				   END
					   + SUM(
							 CASE
								 WHEN (PERIODOI_DATA.EMP_TYPE = 9)
									  OR (PERIODOI_DATA.EMP_TYPE = 2
										  AND PERIODOI_DATA.ARTIST_KIND = 0
										  AND PERIODOI_DATA.ARTIST_TYPE = 0)
									 AND NOT (
										 (0 = 1)
										 AND (PERIODOI_DATA.ID_CMP IN (364, 365))
										 AND (PERIODOI_DATA.EMP_TYPE = 9)
										 AND (PERIODOI_DATA.ARTIST_KIND = 0)
										 AND (PERIODOI_DATA.GTHORN_CALC_VAT_PLIROTEO = 0)
									 )
									 THEN ISNULL(PERIODOI_DATA.VAT_VALUE, 0)
								 ELSE 0
							 END
						 )
					   + 0
					   + SUM(ISNULL(MK.KRAT_ERZ_SYN, 0)) AS KATHARESAPODOXES,
				   SUM(
					   CASE
						   WHEN PERIODOI_DATA.EMP_CATEGORY = 2
							   THEN ISNULL(ISOP.ISOP_KATHARA, 0)
									- ISNULL(ISOP.ISOP_POSO_ERGAZ, 0)
									+ ISNULL(MK.POSO_ERGAZ_2, 0)
									+ ISNULL(MK.POSO_ERGAZ_1, 0)
						   WHEN NOT (
									(PERIODOI_DATA.EMP_TYPE = 2 AND PERIODOI_DATA.artist_type = 6)
									OR (ISNULL(PERIODOI_DATA.OAED_EPID, 0) = 1
										AND ISNULL(OAED_EMP_TYPE, 0) IN (22, 23))
								)
							   THEN ISNULL(PERIODOI_DATA.M_APODOXES, 0)
						   ELSE 0
					   END
					   + ISNULL(MK.POSO_ERGOD_2, 0)
					   + ISNULL(MK.POSO_ERGOD_1, 0)
					   + ISNULL(PP.PAROXES_POSO_ERGOD, 0)
				   )
					   + CASE
							 WHEN PERIODOI_DATA.EMP_TYPE = 2
								  AND PERIODOI_DATA.artist_type = 6
								 THEN ISNULL(MK.POSO_ERGAZ_1, 0) + ISNULL(MK.POSO_ERGAZ_2, 0)
							 ELSE 0
						 END
					   + SUM(
							 CASE
								 WHEN (PERIODOI_DATA.EMP_TYPE = 9)
									  OR (PERIODOI_DATA.EMP_TYPE = 2
										  AND PERIODOI_DATA.ARTIST_KIND = 0
										  AND PERIODOI_DATA.ARTIST_TYPE = 0)
									 AND NOT (
										 (0 = 1)
										 AND (PERIODOI_DATA.ID_CMP IN (364, 365))
										 AND (PERIODOI_DATA.EMP_TYPE = 9)
										 AND (PERIODOI_DATA.ARTIST_KIND = 0)
										 AND (PERIODOI_DATA.GTHORN_CALC_VAT_PLIROTEO = 0)
									 )
									 THEN ISNULL(PERIODOI_DATA.VAT_VALUE, 0)
								 ELSE 0
							 END
						 )
					   - SUM(
							 CASE
								 WHEN PERIODOI_DATA.EK_MET = 1
									 THEN ISNULL(PERIODOI_DATA.ILL_EPID, 0)
								 ELSE 0
							 END
						 )
					   - SUM(
							 CASE
								 WHEN PERIODOI_DATA.EK_MET = 1
									 THEN ISNULL(PERIODOI_DATA.ILL_EPID1, 0)
								 ELSE 0
							 END
						 )
					   - SUM(
							 CASE
								 WHEN PERIODOI_DATA.EK_MET = 1
									 THEN ISNULL(PERIODOI_DATA.LOXIA_EPID, 0)
								 ELSE 0
							 END
						 )
					   + SUM(
							 CASE
								 WHEN CMP.NOCALC_XARTOSHMO_PLIROTEO = 1
									  AND ISNULL(CMP.MELH_DS_XART, 0) = 0
									  AND (
										  PERIODOI_DATA.EMP_TYPE IN (2, 9)
										  OR (
											  PERIODOI_DATA.EMP_TYPE = 4
											  AND PERIODOI_DATA.EMP_SPECIAL_TYPE IN (12, 20)
										  )
									  )
									 THEN dbo.ufn_XARTOSHMO_VALUE(
											  PERIODOI_DATA.ID_EMP,
											  PERIODOI_DATA.XRISI,
											  PERIODOI_DATA.ID_PERIODOS,
											  0
										  )
								 ELSE 0
							 END
						 )
					   + SUM(ISNULL(MK.KRAT_ERZ_SYN, 0)) AS SINOLIKOKOSTOS,
				   SUM(
					   CASE
						   WHEN (PERIODOI_DATA.EMP_TYPE = 9)
								OR (PERIODOI_DATA.EMP_TYPE = 2
									AND PERIODOI_DATA.ARTIST_KIND = 0
									AND PERIODOI_DATA.ARTIST_TYPE = 0)
							   THEN ISNULL(PERIODOI_DATA.VAT_VALUE, 0)
						   ELSE 0
					   END
				   ) AS VAT_VALUE,
				   dbo.ufn_grkl(PERIODOI_DATA.REMS) AS REMS,
				   ISNULL(TAMEIO.DESCR, '9999') AS TAMEIO_DESCR,
				   EMPLOYEE.CODE,
				   SUM(
					   CASE
						   WHEN PERIODOI_DATA.EMP_TYPE = 2
								OR (PERIODOI_DATA.EMP_TYPE = 9 AND PERIODOI_DATA.artist_type = 10)
								OR (PERIODOI_DATA.EMP_TYPE = 4
									AND PERIODOI_DATA.EMP_SPECIAL_TYPE IN (12, 20, 21, 23))
							   THEN ISNULL(
										ROUND(
											dbo.UFN_XARTOSHMO_VALUE(
												PERIODOI_DATA.ID_EMP,
												PERIODOI_DATA.XRISI,
												PERIODOI_DATA.ID_PERIODOS,
												0
											),
											2
										),
										0
									)
						   ELSE 0
					   END
				   ) AS XARTOSHMO,
				   SUM(ISNULL(POSO_ERGOD_3, 0)) AS POSO_ERGOD_3,
				   SUM(ISNULL(POSO_ERGAZ_3, 0)) AS POSO_ERGAZ_3,
				   SUM(ISNULL(KRAT_ika.POSO_ERGOD, 0)) AS POSO_ERGOD_ika,
				   SUM(ISNULL(KRAT_ika.POSO_ERGAZ, 0)) AS POSO_ERGAZ_ika,
				   SUM(ISNULL(KRAT_EPIK.POSO_ERGOD, 0)) AS POSO_ERGOD_EPIK,
				   SUM(ISNULL(KRAT_EPIK.POSO_ERGAZ, 0)) AS POSO_ERGAZ_EPIK,
				   CAST(NULL AS VARCHAR) AS TPTE,
				   CAST(NULL AS VARCHAR) AS TPTE_TEKA,
				   CAST(NULL AS VARCHAR) AS AMOE,
				   SUM(
					   ISNULL(MK.POSO_ERGAZ_SYNERGASIA_1, 0)
					   + ISNULL(MK.POSO_ERGAZ_SYNERGASIA_2, 0)
				   ) AS KRAT_ERGAZ_SYNERGASIA,
				   SUM(
					   CASE
						   WHEN PERIODOI_DATA.EMP_TYPE IN (5, 10)
								AND ISNULL(PERIODOI_DATA.SSE_WEEK_HOURS_TCHR, 0) > 0
							   THEN dbo.eRound(
										(PERIODOI_DATA.WEEK_HOURS_TCHR / PERIODOI_DATA.SSE_WEEK_HOURS_TCHR) * 166.67,
										2
									)
						   ELSE 0
					   END
				   ) AS NNT_VAL,
				   ISNULL(PERIODOI_DATA.TEI_EPIDOTHSH, 0)
					   + ISNULL(PERIODOI_DATA.PROKATAVOLI, 0)
					   + ISNULL(
							 (
								 SELECT SUM(PERIODOS_PAROXES.POSO)
								 FROM PERIODOS_PAROXES
								 WHERE PERIODOS_PAROXES.ID_EMP =
										   PERIODOI_DATA.ID_EMP
								   AND PERIODOS_PAROXES.XRISI =
										   PERIODOI_DATA.XRISI
								   AND PERIODOS_PAROXES.ID_PERIODOS =
										   PERIODOI_DATA.ID_PERIODOS
							 ),
							 0
						 )
					   + SUM(
							 ISNULL(PERIODOI_DATA.STRIKE_SUM, 0)
							 + ISNULL(PERIODOI_DATA.STASI_SUM, 0)
						 ) AS PROKATAVOLI,
				   CAST(NULL AS FLOAT) AS PAROXI,
				   CAST(NULL AS FLOAT) AS TEI_EPIDOTHSH,
				   ISNULL(
					   (
						   SELECT SUM(PERIODOS_PAROXES.POSO_ERGOD)
						   FROM PERIODOS_PAROXES
						   WHERE PERIODOS_PAROXES.ID_EMP = PERIODOI_DATA.ID_EMP
							 AND PERIODOS_PAROXES.XRISI = PERIODOI_DATA.XRISI
							 AND PERIODOS_PAROXES.ID_PERIODOS = PERIODOI_DATA.ID_PERIODOS
					   ),
					   0
				   ) AS PAROXI_ERD,
				   SUM(MK.EPIDOTHSH_OAED) AS EPIDOTHSH_OAED,
				   SUM(
					   dbo.ufn_PLIROTEO(
						   PERIODOI_DATA.id_emp,
						   PERIODOI_DATA.xrisi,
						   PERIODOI_DATA.id_periodos
					   ) + 0
				   ) AS KOSTOSERGOD,
				   CAST(NULL AS FLOAT) AS PASENT_POSO,
				   CAST(NULL AS VARCHAR) AS OD_PROG,
				   CAST(NULL AS VARCHAR) AS DESCR_EP,
				   CAST('-999' AS VARCHAR) AS MIS,
				   0 AS ID,
				   SUM(ISNULL(PANK.M_APODOXES_NOKRAT, 0)) AS M_APODOXES_NOKRAT
			FROM PERIODOI_DATA
				 OUTER APPLY (
					 SELECT *
					 FROM dbo.ufn_GravDays(
							  PERIODOI_DATA.ID_EMP,
							  PERIODOI_DATA.XRISI,
							  PERIODOI_DATA.ID_PERIODOS
						  )
					 WHERE PERIODOI_DATA.CALCTYPE1 = 2
				 ) V2
				 JOIN (
					 SELECT PD.ID_EMP,
							PD.OAED_MIS
					 FROM PERIODOI_DATA PD
					 WHERE PD.ID_PERIODOS = 0
					   AND PD.XRISI = 0
				 ) PDP
					 ON PDP.ID_EMP = PERIODOI_DATA.ID_EMP
				 LEFT JOIN GRADATIONS GR
					 ON GR.GID = PERIODOI_DATA.GRADATION1
				 LEFT JOIN ADMINISTRATION AD
					 ON AD.ID_ADMIN = PERIODOI_DATA.ID_ADMINISTRATION
				 LEFT JOIN ADMINISTRATION_SUB ADS
					 ON ADS.ID_ADMINS = PERIODOI_DATA.ID_ADMINISTRATION_SUB
				 LEFT JOIN V_MISTHODOTIKH_KRATHSEIS MK
					 ON PERIODOI_DATA.ID_PERIODOS = MK.ID_PERIODOS
					AND PERIODOI_DATA.ID_EMP = MK.ID_EMP
					AND PERIODOI_DATA.XRISI = MK.XRISI
				 LEFT JOIN (
					 SELECT PA.ID_PERIODOS,
							PA.XRISI,
							PA.ID_EMP,
							MAX(ISNULL(T.DESCR, '')) AS DESCR
					 FROM PERIODOS_APOD PA
						  JOIN PER_KRATISEIS PK
							  ON PK.ID_PERIODOS_APOD = PA.ID_PERIODOS_APOD
						  JOIN TAMEIA T
							  ON T.ID_TAMEIO = PK.ID_TAMEIO
							 AND T.IS_BAREA = 1
						  JOIN OM_TAMEIA OT
							  ON OT.ID_TAMEIO = T.ID_TAMEIO
							 AND OT.IS_MAIN = 1
					 GROUP BY PA.ID_PERIODOS,
							  PA.XRISI,
							  PA.ID_EMP
				 ) AS TAMEIO
					 ON TAMEIO.ID_PERIODOS = PERIODOI_DATA.ID_PERIODOS
					AND TAMEIO.XRISI = PERIODOI_DATA.XRISI
					AND TAMEIO.ID_EMP = PERIODOI_DATA.ID_EMP
				 LEFT JOIN V_PERIODOS_PAROXES PP
					 ON PERIODOI_DATA.ID_EMP = PP.ID_EMP
					AND PERIODOI_DATA.XRISI = PP.XRISI
					AND PERIODOI_DATA.ID_PERIODOS = PP.ID_PERIODOS
				 JOIN CMP_YPOKAT
					 ON CMP_YPOKAT.COD_YPOKAT = PERIODOI_DATA.COD_YPOKAT
					AND CMP_YPOKAT.ID_CMP = PERIODOI_DATA.ID_CMP
				 LEFT JOIN (
					 SELECT SUM(
								PA.M_APODOXES
								- ISNULL(PA.FMY_SINEK, 0)
								- ISNULL(PA.FMY_EKT_EISF_APOD, 0)
							) AS ISOP_KATHARA,
							/*SUM(IsNull(PK.POSO_ERGAZ,0))*/ 0.00 AS ISOP_POSO_ERGAZ,
							PA.ID_EMP,
							PA.XRISI,
							PA.ID_PERIODOS
					 FROM PERIODOS_APOD PA
						  LEFT JOIN (
							  SELECT ID_PERIODOS_APOD,
									 SUM(ISNULL(POSO_ERGAZ, 0)) AS POSO_ERGAZ
							  FROM PER_KRATISEIS PK
							  GROUP BY ID_PERIODOS_APOD
						  ) PK
							  ON PK.ID_PERIODOS_APOD = PA.ID_PERIODOS_APOD
					 WHERE PA.ID_APODOXHS = 11000
					 GROUP BY PA.ID_EMP,
							  PA.XRISI,
							  PA.ID_PERIODOS
				 ) AS ISOP
					 ON ISOP.ID_PERIODOS = PERIODOI_DATA.ID_PERIODOS
					AND ISOP.ID_EMP = PERIODOI_DATA.ID_EMP
					AND ISOP.XRISI = PERIODOI_DATA.XRISI
				 LEFT JOIN (
					 SELECT dbo.PERIODOI_DATA.ID_EMP,
							dbo.PERIODOI_DATA.XRISI,
							dbo.PERIODOI_DATA.ID_PERIODOS,
							SUM(dbo.PER_KRATISEIS.POSO_ERGAZ) AS POSO_ERGAZ,
							SUM(dbo.PER_KRATISEIS.POSO_ERGOD) AS POSO_ERGOD
					 FROM dbo.PER_KRATISEIS
						  JOIN dbo.PERIODOS_APOD
							  ON dbo.PERIODOS_APOD.ID_PERIODOS_APOD = dbo.PER_KRATISEIS.ID_PERIODOS_APOD
						  JOIN dbo.PERIODOI_DATA
							  ON dbo.PERIODOI_DATA.ID_EMP = dbo.PERIODOS_APOD.ID_EMP
							 AND dbo.PERIODOI_DATA.XRISI = dbo.PERIODOS_APOD.XRISI
							 AND dbo.PERIODOI_DATA.ID_PERIODOS = dbo.PERIODOS_APOD.ID_PERIODOS
						  JOIN dbo.TAMEIA
							  ON dbo.TAMEIA.ID_TAMEIO = dbo.PER_KRATISEIS.ID_TAMEIO
						  LEFT OUTER JOIN dbo.OM_TAMEIA
							  ON dbo.OM_TAMEIA.ID_OMADA = dbo.PERIODOI_DATA.ID_OMADA
							 AND dbo.OM_TAMEIA.ID_TAMEIO = dbo.PER_KRATISEIS.ID_TAMEIO
					 WHERE (dbo.TAMEIA.IS_IKA = 1)
					 GROUP BY dbo.PERIODOI_DATA.ID_EMP,
							  dbo.PERIODOI_DATA.XRISI,
							  dbo.PERIODOI_DATA.ID_PERIODOS
				 ) AS KRAT_IKA
					 ON KRAT_IKA.ID_EMP = PERIODOI_DATA.ID_EMP
					AND KRAT_IKA.XRISI = PERIODOI_DATA.XRISI
					AND KRAT_IKA.ID_PERIODOS = PERIODOI_DATA.ID_PERIODOS
				 LEFT JOIN (
					 SELECT dbo.PERIODOI_DATA.ID_EMP,
							dbo.PERIODOI_DATA.XRISI,
							dbo.PERIODOI_DATA.ID_PERIODOS,
							SUM(dbo.PER_KRATISEIS.POSO_ERGAZ) AS POSO_ERGAZ,
							SUM(dbo.PER_KRATISEIS.POSO_ERGOD) AS POSO_ERGOD
					 FROM dbo.PER_KRATISEIS
						  JOIN dbo.PERIODOS_APOD
							  ON dbo.PERIODOS_APOD.ID_PERIODOS_APOD = dbo.PER_KRATISEIS.ID_PERIODOS_APOD
						  JOIN dbo.PERIODOI_DATA
							  ON dbo.PERIODOI_DATA.ID_EMP = dbo.PERIODOS_APOD.ID_EMP
							 AND dbo.PERIODOI_DATA.XRISI = dbo.PERIODOS_APOD.XRISI
							 AND dbo.PERIODOI_DATA.ID_PERIODOS = dbo.PERIODOS_APOD.ID_PERIODOS
						  JOIN dbo.TAMEIA
							  ON dbo.TAMEIA.ID_TAMEIO = dbo.PER_KRATISEIS.ID_TAMEIO
						  LEFT OUTER JOIN dbo.OM_TAMEIA
							  ON dbo.OM_TAMEIA.ID_OMADA = dbo.PERIODOI_DATA.ID_OMADA
							 AND dbo.OM_TAMEIA.ID_TAMEIO = dbo.PER_KRATISEIS.ID_TAMEIO
					 WHERE (dbo.TAMEIA.IS_IKA = 0)
					   AND dbo.PER_KRATISEIS.ID_TAMEIO NOT IN (
							   59, 60, 61, 62, 156, 179, 180, 237, 239, 240, 286, 327, 346,
							   365, 366, 394, 430, 452, 453, 454, 455, 456, 457, 458, 459,
							   460, 484, 485, 463, 464, 465, 466, 467, 471, 472, 473, 475,
							   476, 5036, 5037, 5038, 5039, 5046, 5050, 5051, 5052, 5054,
							   5055, 5137, 5292, 500, 501, 84, 85, 88, 89, 142, 143, 192,
							   284, 328, 329, 330, 354, 403, 404, 405, 406, 407, 408, 409,
							   410, 411, 413, 414, 415, 417, 418, 419, 420, 421, 422, 423,
							   424, 431, 516, 5040, 5041, 5042, 5043, 5044, 5045, 5049,
							   5053, 5056, 5057, 5058, 5119, 534, 535
						   )
					 GROUP BY dbo.PERIODOI_DATA.ID_EMP,
							  dbo.PERIODOI_DATA.XRISI,
							  dbo.PERIODOI_DATA.ID_PERIODOS
				 ) AS KRAT_EPIK
					 ON KRAT_EPIK.ID_EMP = PERIODOI_DATA.ID_EMP
					AND KRAT_EPIK.XRISI = PERIODOI_DATA.XRISI
					AND KRAT_EPIK.ID_PERIODOS = PERIODOI_DATA.ID_PERIODOS
				 LEFT JOIN (
					 SELECT PA.ID_EMP,
							PA.XRISI,
							PA.ID_PERIODOS,
							SUM(ISNULL(PA.M_APODOXES_NOKRAT, 0)) AS M_APODOXES_NOKRAT
					 FROM PERIODOS_APOD PA
					 GROUP BY PA.ID_EMP,
							  PA.XRISI,
							  PA.ID_PERIODOS
				 ) PANK
					 ON PERIODOI_DATA.ID_EMP = PANK.ID_EMP
					AND PERIODOI_DATA.XRISI = PANK.XRISI
					AND PERIODOI_DATA.ID_PERIODOS = PANK.ID_PERIODOS,
				 PERIODOI,
				 EMPLOYEE,
				 CMP
			WHERE PERIODOI_DATA.ID_EMP = EMPLOYEE.ID_EMP
			  AND PERIODOI_DATA.ID_CMP = CMP.ID_CMP
			  AND PERIODOI_DATA.ID_PERIODOS = PERIODOI.ID_PERIODOS
			  AND PERIODOI_DATA.ID_CMP IN (@pCompanyId)
			  AND PERIODOI_DATA.ID_EMP IN (@@Employees)
			  AND PERIODOI_DATA.XRISI = @pYear
			  AND PERIODOI_DATA.PERIODOS_DATE BETWEEN @pStartingDate AND @pEndingDate
			  AND (
					  (
						  PERIODOI_DATA.ID_PERIODOS IN (
							  19, 21, 27, 29, 37, 38, 39, 49, 50,
							  51, 52, 53, 54, 55, 67, 68, 69, 70,
							  71, 72, 73, 74, 75, 76, 77
						  )
						  OR ISNULL(PERIODOI_DATA.M_APODOXES, 0) > 0
						  --OR ISNULL(PERIODOI_DATA.M_APODOXES, 0) <= 0.001
						  OR ISNULL(PERIODOI_DATA.DURING_OAED_TOK, 0) = 1
					  )
				  )
			  AND (1 = 1)
			  AND (
					  PERIODOI_DATA.EMP_TYPE IS NULL
					  OR NOT (PERIODOI_DATA.EMP_TYPE = 6)
				  )
			  AND PERIODOI_DATA.ID_CMP IN (@pCompanyId)
			GROUP BY EMPLOYEE.AM_IKA,
					 PERIODOI_DATA.ARTIST_TYPE,
					 PERIODOI_DATA.EMP_TYPE,
					 PERIODOI_DATA.EMP_SPECIAL_TYPE,
					 PERIODOI_DATA.ID_CMP,
					 dbo.ufn_grkl(CMP.NAME),
					 CMP.NOCALC_XARTOSHMO_PLIROTEO,
					 PERIODOI_DATA.ID_PERIODOS,
					 PERIODOI_DATA.PERIODOS_DATE,
					 PERIODOI_DATA.TMHMA,
					 AD.DESCR,
					 AD.CODE,
					 ADS.CODE,
					 ADS.DESCR,
					 PERIODOI_DATA.ID_CMP,
					 dbo.ufn_grkl(EMPLOYEE.SURNAME),
					 PERIODOI_DATA.EMP_KIND,
					 PERIODOI_DATA.ID_EMP,
					 EMPLOYEE.SVAT,
					 PERIODOI_DATA.XRISI,
					 EMPLOYEE.FTHRNAME,
					 PERIODOI.DESCR,
					 PERIODOI_DATA.EK_MET,
					 PERIODOI_DATA.GRADATION1,
					 GR.DESCR,
					 EMPLOYEE.NAME,
					 dbo.tekmWORKING_DAYS(
						 PERIODOI_DATA.ID_EMP,
						 PERIODOI_DATA.XRISI,
						 PERIODOI_DATA.ID_PERIODOS,
						 PERIODOI_DATA.WORKING_DAYS
						 - CASE
							   WHEN PERIODOI_DATA.CALCTYPE1 = 2
								   THEN dbo.eRound(ISNULL(V2.GRV_LOXIA_DAYS_NO_ASF, 0), 0)
							   ELSE ISNULL(PERIODOI_DATA.LOXIA_NO_ASF, 0)
						   END
					 ),
					 PERIODOI_DATA.RWORKING_HOURS,
					 PERIODOI_DATA.SPC_DESCR,
					 PERIODOI_DATA.FMY,
					 PERIODOI_DATA.FMY_EKT_EISF,
					 PERIODOI_DATA.M_APODOXES,
					 PERIODOI_DATA.PLIROTEO,
					 PERIODOI_DATA.S_KOSTOS,
					 PERIODOI_DATA.PROKATAVOLI,
					 PERIODOI_DATA.TEI_EPIDOTHSH,
					 PERIODOI_DATA.MERIKH_APASX,
					 PERIODOI_DATA.SALARY_AGREED,
					 PERIODOI_DATA.MERIKI_SALARY_AGREED,
					 CASE
						 WHEN PERIODOI_DATA.MERIKH_APASX = 1
							 THEN PERIODOI_DATA.MERIKI_SALARY_AGREED
						 ELSE PERIODOI_DATA.SALARY_AGREED
					 END,
					 MK.LOIPESAPOD,
					 MK.APODPERIODOY,
					 MK.POSO_ERGOD_2,
					 MK.POSO_ERGOD_1,
					 MK.POSO_ERGAZ_2,
					 MK.POSO_ERGAZ_1,
					 MK.POSO_ERGAZ_TAPIT,
					 MK.POSO_ERGOD_TAPIT,
					 PERIODOI_DATA.EMP_CATEGORY,
					 PERIODOI_DATA.OAED_EPID,
					 PERIODOI_DATA.OAED_EMP_TYPE,
					 CMP_YPOKAT.COD_YPOKAT,
					 CMP_YPOKAT.DESCR,
					 PERIODOI_DATA.REMS,
					 EMPLOYEE.CODE,
					 PERIODOI_DATA.EMP_SPECIAL_TYPE,
					 MK.POSO_AGAINST,
					 MK.KRAT_ERZ_SYN,
					 MK.POSO_ERGAZ_SYNERGASIA_1,
					 MK.POSO_ERGAZ_SYNERGASIA_2,
					 ISNULL(TAMEIO.DESCR, '9999');
		";

        public static string Efka => @"
			SELECT 
				A.TotalContribution
				, A.MODE AS Mode
			FROM 
				APD_GENERAL AS A
				JOIN CMP ON CMP.ID_CMP = A.ID_CMP
			WHERE  
				CMP.ID_CMP IN (@pCompanyId)
				AND A.MONTHFROM = @pPeriod
				AND A.YEARFROM = @pYear
		";
    }
}
