using App.Core.Domain.Traders;

namespace App.Web.Infra.Queries.Payroll
{
    public class PayrollCheckQuery : TraderFactoryQuery
    {
        public PayrollCheckQuery(int logistikiProgramTypeId, int categoryBookTypeId) : base(logistikiProgramTypeId, categoryBookTypeId)
        {
        }

        public override string SoftOne_C => @"
            SELECT 
                SUM(CASE WHEN A.PERIOD = 1 THEN A.CREDIT ELSE 0 END) AS Jan,
                SUM(CASE WHEN A.PERIOD = 2 THEN A.CREDIT ELSE 0 END) AS Feb,
                SUM(CASE WHEN A.PERIOD = 3 THEN A.CREDIT ELSE 0 END) AS Mar,
                SUM(CASE WHEN A.PERIOD = 4 THEN A.CREDIT ELSE 0 END) AS Apr,
                SUM(CASE WHEN A.PERIOD = 5 THEN A.CREDIT ELSE 0 END) AS May,
                SUM(CASE WHEN A.PERIOD = 6 THEN A.CREDIT ELSE 0 END) AS Jun,
                SUM(CASE WHEN A.PERIOD = 7 THEN A.CREDIT ELSE 0 END) AS Jul,
                SUM(CASE WHEN A.PERIOD = 8 THEN A.CREDIT ELSE 0 END) AS Aug,
                SUM(CASE WHEN A.PERIOD = 9 THEN A.CREDIT ELSE 0 END) AS Sep,
                SUM(CASE WHEN A.PERIOD = 10 THEN A.CREDIT ELSE 0 END) AS Oct,
                SUM(CASE WHEN A.PERIOD = 11 THEN A.CREDIT ELSE 0 END) AS Nov,
                SUM(CASE WHEN A.PERIOD = 12 THEN A.CREDIT ELSE 0 END) AS Dec
            FROM 
                ACNHEADER A 
            WHERE 
                A.SODTYPE = 89 
                AND A.FPRMS = 5003 
                AND A.SOSOURCE = 1089 
                AND A.COMPANY = @pCompanyId 
                AND A.FISCPRD = @pYear
        ";

        public override string SoftOne_B => @"
            SELECT 
                SUM(CASE WHEN A.PERIOD = 1 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Jan,
                SUM(CASE WHEN A.PERIOD = 2 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Feb,
                SUM(CASE WHEN A.PERIOD = 3 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Mar,
                SUM(CASE WHEN A.PERIOD = 4 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Apr,
                SUM(CASE WHEN A.PERIOD = 5 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS May,
                SUM(CASE WHEN A.PERIOD = 6 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Jun,
                SUM(CASE WHEN A.PERIOD = 7 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Jul,
                SUM(CASE WHEN A.PERIOD = 8 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Aug,
                SUM(CASE WHEN A.PERIOD = 9 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Sep,
                SUM(CASE WHEN A.PERIOD = 10 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Oct,
                SUM(CASE WHEN A.PERIOD = 11 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Nov,
                SUM(CASE WHEN A.PERIOD = 12 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Dec
            FROM 
            (
                SELECT 
                    M.COMPANY,M.SODTYPE,M.MTRL,M.CODE,M.NAME,M.MTRTYPE,M.MTRTYPE1
                FROM 
                    MTRL M
                WHERE 
                    M.COMPANY = @pCompanyId 
                    AND M.SODTYPE = 61 
                    AND (M.CODE LIKE '60.01%' OR M.CODE LIKE '60.02%')
            ) AS X
            JOIN MTRBALSHEET A ON X.MTRL = A.MTRL 
            WHERE 
                A.COMPANY = @pCompanyId
                AND A.FISCPRD = @pYear
                AND A.PERIOD IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)
        ";

        public override string Prosvasis => @"
            SELECT 
                SUM(CASE WHEN A.PERIOD = 1 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Jan,
                SUM(CASE WHEN A.PERIOD = 2 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Feb,
                SUM(CASE WHEN A.PERIOD = 3 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Mar,
                SUM(CASE WHEN A.PERIOD = 4 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Apr,
                SUM(CASE WHEN A.PERIOD = 5 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS May,
                SUM(CASE WHEN A.PERIOD = 6 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Jun,
                SUM(CASE WHEN A.PERIOD = 7 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Jul,
                SUM(CASE WHEN A.PERIOD = 8 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Aug,
                SUM(CASE WHEN A.PERIOD = 9 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Sep,
                SUM(CASE WHEN A.PERIOD = 10 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Oct,
                SUM(CASE WHEN A.PERIOD = 11 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Nov,
                SUM(CASE WHEN A.PERIOD = 12 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Dec
            FROM 
            (
                SELECT 
                    M.COMPANY,M.SODTYPE,M.MTRL,M.CODE,M.NAME,M.MTRTYPE,M.MTRTYPE1
                FROM 
                    MTRL M
                WHERE 
                    M.COMPANY = @pCompanyId 
                    AND M.SODTYPE = 61 
                    AND (M.CODE LIKE '60.01%' OR M.CODE LIKE '60.02%')
            ) AS X
            JOIN MTRBALSHEET A ON X.MTRL = A.MTRL 
            WHERE 
                A.COMPANY = @pCompanyId
                AND A.FISCPRD = @pYear
                AND A.PERIOD IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)
        ";

        public override string Prosvasis_C => @"
            SELECT 
                SUM(CASE WHEN A.PERIOD = 1 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Jan,
                SUM(CASE WHEN A.PERIOD = 2 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Feb,
                SUM(CASE WHEN A.PERIOD = 3 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Mar,
                SUM(CASE WHEN A.PERIOD = 4 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Apr,
                SUM(CASE WHEN A.PERIOD = 5 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS May,
                SUM(CASE WHEN A.PERIOD = 6 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Jun,
                SUM(CASE WHEN A.PERIOD = 7 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Jul,
                SUM(CASE WHEN A.PERIOD = 8 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Aug,
                SUM(CASE WHEN A.PERIOD = 9 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Sep,
                SUM(CASE WHEN A.PERIOD = 10 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Oct,
                SUM(CASE WHEN A.PERIOD = 11 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Nov,
                SUM(CASE WHEN A.PERIOD = 12 THEN A.IMPVAL - A.EXPVAL ELSE 0 END) AS Dec
            FROM 
            (
                SELECT 
                    M.COMPANY,M.SODTYPE,M.MTRL,M.CODE,M.NAME,M.MTRTYPE,M.MTRTYPE1
                FROM 
                    MTRL M
                WHERE 
                    M.COMPANY = @pCompanyId 
                    AND M.SODTYPE = 61 
                    AND (M.CODE LIKE '60.01%' OR M.CODE LIKE '60.02%')
            ) AS X
            JOIN MTRBALSHEET A ON X.MTRL = A.MTRL 
            WHERE 
                A.COMPANY = @pCompanyId
                AND A.FISCPRD = @pYear
                AND A.PERIOD IN (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12)
        ";
        public static string Employer => @"
            SELECT
				SUM(CASE WHEN K.Periodos = 1 THEN K.Value ELSE 0 END) AS Jan,
				SUM(CASE WHEN K.Periodos = 2 THEN K.Value ELSE 0 END) AS Feb,
				SUM(CASE WHEN K.Periodos = 3 THEN K.Value ELSE 0 END) AS Mar,
				SUM(CASE WHEN K.Periodos = 4 THEN K.Value ELSE 0 END) AS Apr,
				SUM(CASE WHEN K.Periodos = 5 THEN K.Value ELSE 0 END) AS May,
				SUM(CASE WHEN K.Periodos = 6 THEN K.Value ELSE 0 END) AS Jun,
				SUM(CASE WHEN K.Periodos = 7 THEN K.Value ELSE 0 END) AS Jul,
				SUM(CASE WHEN K.Periodos = 8 THEN K.Value ELSE 0 END) AS Aug,
				SUM(CASE WHEN K.Periodos = 9 THEN K.Value ELSE 0 END) AS Sep,
				SUM(CASE WHEN K.Periodos = 10 THEN K.Value ELSE 0 END) AS Oct,
				SUM(CASE WHEN K.Periodos = 11 THEN K.Value ELSE 0 END) AS Nov,
				SUM(CASE WHEN K.Periodos = 12 THEN K.Value ELSE 0 END) AS Dec
			FROM
				(SELECT 
					MONTH(x.PERIODOS_DATE) AS Periodos, 
					SUM(x.SINOLIKOKOSTOS) AS Value
				FROM (
					SELECT --DISTINCT 
						PERIODOI_DATA.PERIODOS_DATE, 
						SUM(
							CASE 
								WHEN PERIODOI_DATA.EMP_CATEGORY = 2 
								THEN ISNULL(ISOP.ISOP_KATHARA, 0) - ISNULL(ISOP.ISOP_POSO_ERGAZ, 0) + ISNULL(MK.POSO_ERGAZ_2, 0) + ISNULL(MK.POSO_ERGAZ_1, 0) 
								WHEN NOT ((periodoi_data.EMP_TYPE = 2 AND periodoi_data.artist_type = 6) OR (ISNULL(periodoi_data.OAED_EPID, 0) = 1 AND ISNULL(OAED_EMP_TYPE, 0) IN (22, 23))) 
								THEN ISNULL(PERIODOI_DATA.M_APODOXES, 0) 
								ELSE 0 
							END + ISNULL(MK.POSO_ERGOD_2, 0) + ISNULL(MK.POSO_ERGOD_1, 0) + ISNULL(PP.PAROXES_POSO_ERGOD, 0)
						) + (
							CASE 
								WHEN periodoi_data.EMP_TYPE = 2 AND periodoi_data.artist_type = 6 
								THEN ISNULL(MK.POSO_ERGAZ_1, 0) + ISNULL(MK.POSO_ERGAZ_2, 0) 
								ELSE 0 
							END
						) + SUM(
							CASE 
								WHEN ((PERIODOI_DATA.EMP_TYPE = 9) OR ((PERIODOI_DATA.EMP_TYPE = 2) AND (PERIODOI_DATA.ARTIST_KIND = 0) AND (PERIODOI_DATA.ARTIST_TYPE = 0))) 
								AND NOT ((0 = 1) AND (PERIODOI_DATA.ID_CMP IN (364, 365)) AND (PERIODOI_DATA.EMP_TYPE = 9) AND (PERIODOI_DATA.ARTIST_KIND = 0) AND (PERIODOI_DATA.GTHORN_CALC_VAT_PLIROTEO = 0)) 
								THEN ISNULL(PERIODOI_DATA.VAT_VALUE, 0) 
								ELSE 0 
							END
						) - SUM(
							CASE 
								WHEN PERIODOI_DATA.EK_MET = 1 
								THEN ISNULL(PERIODOI_DATA.ILL_EPID, 0) 
								ELSE 0 
							END
						) - SUM(
							CASE 
								WHEN PERIODOI_DATA.EK_MET = 1 
								THEN ISNULL(PERIODOI_DATA.ILL_EPID1, 0) 
								ELSE 0 
							END
						) - SUM(
							CASE 
								WHEN PERIODOI_DATA.EK_MET = 1 
								THEN ISNULL(PERIODOI_DATA.LOXIA_EPID, 0) 
								ELSE 0 
							END
						) + SUM(
							CASE 
								WHEN (cmp.NOCALC_XARTOSHMO_PLIROTEO = 1 AND ISNULL(CMP.MELH_DS_XART, 0) = 0) AND (PERIODOI_DATA.EMP_TYPE IN (2, 9) OR (PERIODOI_DATA.EMP_TYPE = 4 AND PERIODOI_DATA.EMP_SPECIAL_TYPE IN (12, 20))) 
								THEN dbo.ufn_XARTOSHMO_VALUE(PERIODOI_DATA.ID_EMP, PERIODOI_DATA.XRISI, PERIODOI_DATA.ID_PERIODOS, 0) 
								ELSE 0 
							END
						) + SUM(ISNULL(MK.KRAT_ERZ_SYN, 0)) AS SINOLIKOKOSTOS, 
						0 AS ID 
					FROM PERIODOI_DATA 
					OUTER APPLY (
						SELECT * 
						FROM dbo.ufn_GravDays(
							PERIODOI_DATA.ID_EMP, 
							PERIODOI_DATA.XRISI, 
							PERIODOI_DATA.ID_PERIODOS
						) 
						WHERE PERIODOI_DATA.CALCTYPE1 = 2
					) V2 
					JOIN (
						SELECT PD.ID_EMP, PD.OAED_MIS 
						FROM PERIODOI_DATA PD 
						WHERE PD.ID_PERIODOS = 0 AND PD.XRISI = 0
					) PDP ON PDP.ID_EMP = PERIODOI_DATA.ID_EMP 
					LEFT JOIN GRADATIONS GR ON GR.GID = PERIODOI_DATA.GRADATION1 
					LEFT JOIN ADMINISTRATION AD ON AD.ID_ADMIN = PERIODOI_DATA.ID_ADMINISTRATION 
					LEFT JOIN ADMINISTRATION_SUB ADS ON ADS.ID_ADMINS = PERIODOI_DATA.ID_ADMINISTRATION_SUB 
					LEFT JOIN V_MISTHODOTIKH_KRATHSEIS MK ON PERIODOI_DATA.ID_PERIODOS = MK.ID_PERIODOS 
					AND PERIODOI_DATA.ID_EMP = MK.ID_EMP 
					AND PERIODOI_DATA.XRISI = MK.XRISI 
					LEFT JOIN (
						SELECT 
							PA.ID_PERIODOS, PA.XRISI, PA.ID_EMP, MAX(ISNULL(T.DESCR, '')) AS DESCR 
						FROM PERIODOS_APOD PA 
						JOIN PER_KRATISEIS PK ON PK.ID_PERIODOS_APOD = PA.ID_PERIODOS_APOD 
						JOIN TAMEIA T ON T.ID_TAMEIO = PK.ID_TAMEIO AND T.IS_BAREA = 1 
						JOIN OM_TAMEIA OT ON OT.ID_TAMEIO = T.ID_TAMEIO AND OT.IS_MAIN = 1 
						GROUP BY PA.ID_PERIODOS, PA.XRISI, PA.ID_EMP
					) AS TAMEIO ON TAMEIO.ID_PERIODOS = PERIODOI_DATA.ID_PERIODOS 
					AND TAMEIO.XRISI = PERIODOI_DATA.XRISI 
					AND TAMEIO.ID_EMP = PERIODOI_DATA.ID_EMP 
					LEFT JOIN V_PERIODOS_PAROXES PP ON PERIODOI_DATA.ID_EMP = PP.ID_EMP 
					AND PERIODOI_DATA.XRISI = PP.XRISI 
					AND PERIODOI_DATA.ID_PERIODOS = PP.ID_PERIODOS 
					JOIN CMP_YPOKAT ON CMP_YPOKAT.COD_YPOKAT = PERIODOI_DATA.COD_YPOKAT 
					AND CMP_YPOKAT.ID_CMP = PERIODOI_DATA.ID_CMP 
					LEFT JOIN (
						SELECT 
							SUM(PA.M_APODOXES - ISNULL(PA.FMY_SINEK, 0) - ISNULL(PA.FMY_EKT_EISF_APOD, 0)) AS ISOP_KATHARA, 
							0.00 AS ISOP_POSO_ERGAZ, 
							PA.ID_EMP, 
							PA.XRISI, 
							PA.ID_PERIODOS 
						FROM PERIODOS_APOD PA 
						LEFT JOIN (
							SELECT ID_PERIODOS_APOD, SUM(ISNULL(POSO_ERGAZ, 0)) AS POSO_ERGAZ 
							FROM PER_KRATISEIS PK 
							GROUP BY ID_PERIODOS_APOD
						) PK ON PK.ID_PERIODOS_APOD = PA.ID_PERIODOS_APOD 
						WHERE PA.ID_APODOXHS = 11000 
						GROUP BY PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS
					) AS ISOP ON ISOP.ID_PERIODOS = PERIODOI_DATA.ID_PERIODOS 
					AND ISOP.ID_EMP = PERIODOI_DATA.ID_EMP 
					AND ISOP.XRISI = PERIODOI_DATA.XRISI 
					LEFT JOIN (
						SELECT 
							dbo.PERIODOI_DATA.ID_EMP, 
							dbo.PERIODOI_DATA.XRISI, 
							dbo.PERIODOI_DATA.ID_PERIODOS, 
							SUM(dbo.PER_KRATISEIS.POSO_ERGAZ) AS POSO_ERGAZ, 
							SUM(dbo.PER_KRATISEIS.POSO_ERGOD) AS POSO_ERGOD 
						FROM dbo.PER_KRATISEIS 
						JOIN dbo.PERIODOS_APOD ON dbo.PERIODOS_APOD.ID_PERIODOS_APOD = dbo.PER_KRATISEIS.ID_PERIODOS_APOD 
						JOIN dbo.PERIODOI_DATA ON dbo.PERIODOI_DATA.ID_EMP = dbo.PERIODOS_APOD.ID_EMP 
						AND dbo.PERIODOI_DATA.XRISI = dbo.PERIODOS_APOD.XRISI 
						AND dbo.PERIODOI_DATA.ID_PERIODOS = dbo.PERIODOS_APOD.ID_PERIODOS 
						JOIN dbo.TAMEIA ON dbo.TAMEIA.ID_TAMEIO = dbo.PER_KRATISEIS.ID_TAMEIO 
						LEFT OUTER JOIN dbo.OM_TAMEIA ON dbo.OM_TAMEIA.ID_OMADA = dbo.PERIODOI_DATA.ID_OMADA 
						AND dbo.OM_TAMEIA.ID_TAMEIO = dbo.PER_KRATISEIS.ID_TAMEIO 
						WHERE dbo.TAMEIA.IS_IKA = 1 
						GROUP BY dbo.PERIODOI_DATA.ID_EMP, dbo.PERIODOI_DATA.XRISI, dbo.PERIODOI_DATA.ID_PERIODOS
					) AS KRAT_IKA ON KRAT_IKA.ID_EMP = PERIODOI_DATA.ID_EMP 
					AND KRAT_IKA.XRISI = PERIODOI_DATA.XRISI 
					AND KRAT_IKA.ID_PERIODOS = PERIODOI_DATA.ID_PERIODOS 
					LEFT JOIN (
						SELECT 
							dbo.PERIODOI_DATA.ID_EMP, 
							dbo.PERIODOI_DATA.XRISI, 
							dbo.PERIODOI_DATA.ID_PERIODOS, 
							SUM(dbo.PER_KRATISEIS.POSO_ERGAZ) AS POSO_ERGAZ, 
							SUM(dbo.PER_KRATISEIS.POSO_ERGOD) AS POSO_ERGOD 
						FROM dbo.PER_KRATISEIS 
						JOIN dbo.PERIODOS_APOD ON dbo.PERIODOS_APOD.ID_PERIODOS_APOD = dbo.PER_KRATISEIS.ID_PERIODOS_APOD 
						JOIN dbo.PERIODOI_DATA ON dbo.PERIODOI_DATA.ID_EMP = dbo.PERIODOS_APOD.ID_EMP 
						AND dbo.PERIODOI_DATA.XRISI = dbo.PERIODOS_APOD.XRISI 
						AND dbo.PERIODOI_DATA.ID_PERIODOS = dbo.PERIODOS_APOD.ID_PERIODOS 
						JOIN dbo.TAMEIA ON dbo.TAMEIA.ID_TAMEIO = dbo.PER_KRATISEIS.ID_TAMEIO 
						LEFT OUTER JOIN dbo.OM_TAMEIA ON dbo.OM_TAMEIA.ID_OMADA = dbo.PERIODOI_DATA.ID_OMADA 
						AND dbo.OM_TAMEIA.ID_TAMEIO = dbo.PER_KRATISEIS.ID_TAMEIO 
						WHERE dbo.TAMEIA.IS_IKA = 0 
						AND dbo.PER_KRATISEIS.ID_TAMEIO NOT IN (
							59, 60, 61, 62, 156, 179, 180, 237, 239, 240, 286, 327, 346, 365, 366, 394, 430, 452, 453, 454, 455, 456, 457, 458, 459, 460, 484, 485, 463, 464, 465, 466, 467, 471, 472, 473, 475, 476, 5036, 5037, 5038, 5039, 5046, 5050, 5051, 5052, 5054, 5055, 5137, 5292, 500, 501, 84, 85, 88, 89, 142, 143, 192, 284, 328, 329, 330, 354, 403, 404, 405, 406, 407, 408, 409, 410, 411, 413, 414, 415, 417, 418, 419, 420, 421, 422, 423, 424, 431, 516, 5040, 5041, 5042, 5043, 5044, 5045, 5049, 5053, 5056, 5057, 5058, 5119, 534, 535
						) 
						GROUP BY dbo.PERIODOI_DATA.ID_EMP, dbo.PERIODOI_DATA.XRISI, dbo.PERIODOI_DATA.ID_PERIODOS
					) AS KRAT_EPIK ON KRAT_EPIK.ID_EMP = PERIODOI_DATA.ID_EMP 
					AND KRAT_EPIK.XRISI = PERIODOI_DATA.XRISI 
					AND KRAT_EPIK.ID_PERIODOS = PERIODOI_DATA.ID_PERIODOS, 
					PERIODOI, 
					EMPLOYEE, 
					CMP 
					WHERE PERIODOI_DATA.ID_EMP = EMPLOYEE.ID_EMP 
					AND PERIODOI_DATA.ID_CMP = CMP.ID_CMP 
					AND PERIODOI_DATA.ID_PERIODOS = PERIODOI.ID_PERIODOS 
					AND PERIODOI_DATA.ID_CMP = @pCompanyId 
					AND PERIODOI_DATA.XRISI IN (@pYear) 
					AND (((PERIODOI_DATA.ID_PERIODOS IN (19, 21, 27, 29, 37, 38, 39, 49, 50, 51, 52, 53, 54, 55, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77) OR ISNULL(PERIODOI_DATA.M_APODOXES, 0) > 0 OR ISNULL(PERIODOI_DATA.M_APODOXES, 0) <= 0.001 OR ISNULL(PERIODOI_DATA.DURING_OAED_TOK, 0) = 1))) 
					AND 1 = 1 
					AND (PERIODOI_DATA.EMP_TYPE IS NULL OR (NOT (PERIODOI_DATA.EMP_TYPE = 6))) 
					GROUP BY 
						PERIODOI_DATA.ARTIST_TYPE, 
						PERIODOI_DATA.EMP_TYPE, 
						PERIODOI_DATA.PERIODOS_DATE,
						MK.POSO_ERGAZ_2, 
						MK.POSO_ERGAZ_1 
				) AS X 
				GROUP BY MONTH(x.PERIODOS_DATE)
			) AS K
        ";
    }
}
