namespace App.Web.Infra.Queries.Payroll
{
    public static partial class PayrollQuery
    {
        //Όλοι οι ενεργοι εργοδότες
        public static string Employers => @"
            SELECT ID_CMP As CompanyId, 
				ISNULL(NAME, '') AS LastName, ISNULL(FRSTNAME, '') AS FirstName, ISNULL(SVAT, '') AS Vat, 
				PROF AS Profession, NOMIKH_MORFH AS LegalFormTypeName, 
				DOYNAME AS DOY, AM_IKA AS AmIka, DESCR AS IkaDescription, ADDR AS Address , NUMBER AS Number, 
				CITY AS City, PHONE AS Phone, EMAIL AS Email, EKPROSOPOS AS Representative, ISACTIVE AS Active,
				CASE CMP_KIND WHEN 0  THEN 'Προσωπική Εταιρία'
					WHEN 1  THEN 'Φυσικό Πρόσωπο'
					WHEN 2  THEN 'Νομικό Πρόσωπο'
					WHEN 3  THEN 'Κοινωνία'
					WHEN 4  THEN 'Κοινοπραξία'
					WHEN 5  THEN 'Άλλο'
					WHEN 6  THEN 'Υπουργείο'
					WHEN 7  THEN 'Περιφέρεια'
					WHEN 8  THEN 'Ν.Α.'
					WHEN 9  THEN 'Ο.Τ.Α.'
					WHEN 10 THEN 'Α.Ε.Ι.'
					WHEN 11 THEN 'Α.Τ.Ε.Ι.'
					WHEN 12 THEN 'Ν.Π.Δ.Δ.'
					WHEN 13 THEN 'Ν.Π.Ι.Δ.'
					WHEN 14 THEN 'Αλλοδαπές Εταιρίες'
					END AS CompanyType, APD_USERNAME AS EmployerIkaUserName, APD_PASSWORD AS EmployerIkaPassword
				FROM vcmplist 
				WHERE ISACTIVE = 1
            ";

        public static string EmployersPerYear => @"
            SELECT 
                V.ID_EMP AS EmployerId
            FROM 
                vpr_WRKListFull(@pYear, 'admin', @pCompanyId, '*', 0, 0) V 
            JOIN 
                CMP C ON V.ID_CMP = C.ID_CMP
                JOIN EMPLOYEE E ON e.ID_EMP = v.ID_EMP 
            WHERE 
                ((v.ID_EMP > 0) or ((v.ID_EMP < 0) and (isnull(e.IsBDGRec,0)=1))) AND V.EMP_ACTIVE = 'ΝΑΙ'
            ";

        public static string EmployerLookupItem => @"
            SELECT ID_CMP As CompanyId, AM_IKA as AmIka, 
				ISNULL(NAME, '') AS LastName, ISNULL(FRSTNAME, '') AS FirstName, FORMAT(CAST(SVAT AS INTEGER), 'D9') AS Vat
				FROM vcmplist
				WHERE ISACTIVE = 1
				ORDER BY NAME
            ";

        public static string InsurancePackages => @"
            SELECT DISTINCT 
	            0 AS Id
	            , O.DESCR AS Description
            	, CAST(ISNULL(A.PERC_ERGAZ, 0) AS DECIMAL(18,4)) AS Employee
            	, CAST(ISNULL(A.PERC_ERGOD, 0) AS DECIMAL(18,4)) AS Employer
            FROM            
	            PERIODOI_DATA AS PD INNER JOIN
	            CMP AS C ON PD.ID_CMP = C.ID_CMP INNER JOIN
	            EMPLOYEE AS E ON PD.ID_EMP = E.ID_EMP INNER JOIN
	            OMADES AS O ON PD.ID_OMADA = O.ID_OMADA LEFT OUTER JOIN
                (SELECT KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, SUM(ISNULL(PK.POSO_ERGAZ, 0)) AS ERGAZ_POSO, SUM(ISNULL(PK.POSO_ERGOD, 0)) AS ERGOD_POSO, 
		            SUM(ISNULL(CASE WHEN ISNULL(PA.FMY_TYPE, 0) = 0 THEN PA.FMY ELSE PA.FMY_SINEK END, 0)) AS FMY, SUM(ISNULL(PA.M_APODOXES, 0)) AS M_APODOXES, SUM(ISNULL(PK.SUM_OAED_EPID, 0)) 
		            AS sum_oaed_epid, K.DESCR AS KRATISI, 5 AS ID_APODOXHS, K.ID_KRATISI, SUM(ISNULL(PK.MIKTA_KRAT, 0)) AS MIKTA_KRAT, MAX(PK.CALC_PERC_ERGAZ) AS PERC_ERGAZ, MAX(PK.CALC_PERC_ERGOD) AS PERC_ERGOD
                FROM PERIODOS_APOD AS PA LEFT OUTER JOIN
		            PER_KRATISEIS AS PK ON PA.ID_PERIODOS_APOD = PK.ID_PERIODOS_APOD LEFT OUTER JOIN
		            KRAT_TAMEIA AS KT ON PK.ID_KRATISI = KT.ID_KRATISI AND PK.ID_TAMEIO = KT.ID_TAMEIO LEFT OUTER JOIN
		            KRATISEIS AS K ON KT.ID_KRATISI = K.ID_KRATISI
	            WHERE
		            (PA.ID_APODOXHS BETWEEN 5 AND 20) OR
		            (PA.ID_APODOXHS BETWEEN 103 AND 106)
                GROUP BY KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, K.DESCR, K.ID_KRATISI
                UNION ALL
                SELECT KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, SUM(ISNULL(PK.POSO_ERGAZ, 0)) AS ERGAZ_POSO, SUM(ISNULL(PK.POSO_ERGOD, 0)) AS ERGOD_POSO, 
		            SUM(ISNULL(CASE WHEN ISNULL(PA.FMY_TYPE, 0) = 0 THEN PA.FMY ELSE PA.FMY_SINEK END, 0)) AS FMY, SUM(ISNULL(PA.M_APODOXES, 0)) AS M_APODOXES, 
		            SUM(ISNULL(PK.SUM_OAED_EPID, 0)) AS sum_oaed_epid, K.DESCR AS KRATISI, CASE WHEN PA.ID_PERIODOS IN (16, 24) THEN 24 WHEN PA.ID_PERIODOS = 17 THEN 25 ELSE 1 END AS ID_APODOXHS, K.ID_KRATISI, 
		            SUM(ISNULL(PK.MIKTA_KRAT, 0)) AS MIKTA_KRAT, MAX(PK.CALC_PERC_ERGAZ) AS PERC_ERGAZ, MAX(PK.CALC_PERC_ERGOD) AS PERC_ERGOD
	            FROM PERIODOS_APOD AS PA LEFT OUTER JOIN
		            PER_KRATISEIS AS PK ON PA.ID_PERIODOS_APOD = PK.ID_PERIODOS_APOD LEFT OUTER JOIN
		            KRAT_TAMEIA AS KT ON PK.ID_KRATISI = KT.ID_KRATISI AND PK.ID_TAMEIO = KT.ID_TAMEIO LEFT OUTER JOIN
		            KRATISEIS AS K ON KT.ID_KRATISI = K.ID_KRATISI
                WHERE (PA.ID_APODOXHS IN (1, 21, 22, 23, 27, 24, 25))
                GROUP BY KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, K.DESCR, K.ID_KRATISI, CASE WHEN PA.ID_PERIODOS IN (16, 24) THEN 24 WHEN PA.ID_PERIODOS = 17 THEN 25 ELSE 1 END
                UNION ALL
                SELECT KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, SUM(ISNULL(PK.POSO_ERGAZ, 0)) AS ERGAZ_POSO, SUM(ISNULL(PK.POSO_ERGOD, 0)) AS ERGOD_POSO, 
		            SUM(ISNULL(CASE WHEN ISNULL(PA.FMY_TYPE, 0) = 0 THEN PA.FMY ELSE PA.FMY_SINEK END, 0)) AS FMY, SUM(ISNULL(PA.M_APODOXES, 0)) AS M_APODOXES, SUM(ISNULL(PK.SUM_OAED_EPID, 0)) 
		            AS sum_oaed_epid, K.DESCR AS KRATISI, 26 AS ID_APODOXHS, K.ID_KRATISI, SUM(ISNULL(PK.MIKTA_KRAT, 0)) AS MIKTA_KRAT, MAX(PK.CALC_PERC_ERGAZ) AS PERC_ERGAZ, MAX(PK.CALC_PERC_ERGOD) AS PERC_ERGOD
                FROM PERIODOS_APOD AS PA LEFT OUTER JOIN
		            PER_KRATISEIS AS PK ON PA.ID_PERIODOS_APOD = PK.ID_PERIODOS_APOD LEFT OUTER JOIN
		            KRAT_TAMEIA AS KT ON PK.ID_KRATISI = KT.ID_KRATISI AND PK.ID_TAMEIO = KT.ID_TAMEIO LEFT OUTER JOIN
		            KRATISEIS AS K ON KT.ID_KRATISI = K.ID_KRATISI
                WHERE (PA.ID_APODOXHS IN (26))
                GROUP BY KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, K.DESCR, K.ID_KRATISI
                UNION ALL
                SELECT KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, SUM(ISNULL(PK.POSO_ERGAZ, 0)) AS ERGAZ_POSO, SUM(ISNULL(PK.POSO_ERGOD, 0)) AS ERGOD_POSO, 
		            SUM(ISNULL(CASE WHEN ISNULL(PA.FMY_TYPE, 0) = 0 THEN PA.FMY ELSE PA.FMY_SINEK END, 0)) AS FMY, SUM(ISNULL(PA.M_APODOXES, 0)) AS M_APODOXES, SUM(ISNULL(PK.SUM_OAED_EPID, 0)) AS sum_oaed_epid, 
		            K.DESCR AS KRATISI, 47 AS ID_APODOXHS, K.ID_KRATISI, SUM(ISNULL(PK.MIKTA_KRAT, 0)) AS MIKTA_KRAT, MAX(PK.CALC_PERC_ERGAZ) AS PERC_ERGAZ, MAX(PK.CALC_PERC_ERGOD) AS PERC_ERGOD
                FROM PERIODOS_APOD AS PA LEFT OUTER JOIN
		            PER_KRATISEIS AS PK ON PA.ID_PERIODOS_APOD = PK.ID_PERIODOS_APOD LEFT OUTER JOIN
		            KRAT_TAMEIA AS KT ON PK.ID_KRATISI = KT.ID_KRATISI AND PK.ID_TAMEIO = KT.ID_TAMEIO LEFT OUTER JOIN
		            KRATISEIS AS K ON KT.ID_KRATISI = K.ID_KRATISI
                WHERE (PA.ID_APODOXHS IN (47, 49, 50))
                GROUP BY KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, K.DESCR, K.ID_KRATISI
                UNION ALL
                SELECT KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, SUM(ISNULL(PK.POSO_ERGAZ, 0)) AS ERGAZ_POSO, SUM(ISNULL(PK.POSO_ERGOD, 0)) AS ERGOD_POSO, 
		            SUM(ISNULL(CASE WHEN ISNULL(PA.FMY_TYPE, 0) = 0 THEN PA.FMY ELSE PA.FMY_SINEK END, 0)) AS FMY, SUM(ISNULL(PA.M_APODOXES, 0)) AS M_APODOXES, SUM(ISNULL(PK.SUM_OAED_EPID, 0)) 
		            AS sum_oaed_epid, K.DESCR AS KRATISI, 2 AS ID_APODOXHS, K.ID_KRATISI, SUM(ISNULL(PK.MIKTA_KRAT, 0)) AS MIKTA_KRAT, MAX(PK.CALC_PERC_ERGAZ) AS PERC_ERGAZ, MAX(PK.CALC_PERC_ERGOD) AS PERC_ERGOD
                FROM PERIODOS_APOD AS PA LEFT OUTER JOIN
		            PER_KRATISEIS AS PK ON PA.ID_PERIODOS_APOD = PK.ID_PERIODOS_APOD LEFT OUTER JOIN
		            KRAT_TAMEIA AS KT ON PK.ID_KRATISI = KT.ID_KRATISI AND PK.ID_TAMEIO = KT.ID_TAMEIO LEFT OUTER JOIN
		            KRATISEIS AS K ON KT.ID_KRATISI = K.ID_KRATISI
                WHERE (PA.ID_APODOXHS BETWEEN 2 AND 4)
                GROUP BY KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, K.DESCR, K.ID_KRATISI
                UNION ALL
                SELECT KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, SUM(ISNULL(PK.POSO_ERGAZ, 0)) AS ERGAZ_POSO, SUM(ISNULL(PK.POSO_ERGOD, 0)) AS ERGOD_POSO, 
		            SUM(ISNULL(CASE WHEN ISNULL(PA.FMY_TYPE, 0) = 0 THEN PA.FMY ELSE PA.FMY_SINEK END, 0)) AS FMY, SUM(ISNULL(PA.M_APODOXES, 0)) AS M_APODOXES, SUM(ISNULL(PK.SUM_OAED_EPID, 0)) 
		            AS sum_oaed_epid, K.DESCR AS KRATISI, PA.ID_APODOXHS, K.ID_KRATISI, SUM(ISNULL(PK.MIKTA_KRAT, 0)) AS MIKTA_KRAT, MAX(PK.CALC_PERC_ERGAZ) AS PERC_ERGAZ, MAX(PK.CALC_PERC_ERGOD) AS PERC_ERGOD
                FROM PERIODOS_APOD AS PA LEFT OUTER JOIN
		            PER_KRATISEIS AS PK ON PA.ID_PERIODOS_APOD = PK.ID_PERIODOS_APOD LEFT OUTER JOIN
		            KRAT_TAMEIA AS KT ON PK.ID_KRATISI = KT.ID_KRATISI AND PK.ID_TAMEIO = KT.ID_TAMEIO LEFT OUTER JOIN
		            KRATISEIS AS K ON KT.ID_KRATISI = K.ID_KRATISI
                WHERE (NOT (PA.ID_APODOXHS BETWEEN 2 AND 4 OR
		            PA.ID_APODOXHS IN (47, 49, 50, 1, 21, 22, 23, 26, 27, 24, 25) OR PA.ID_APODOXHS BETWEEN 5 AND 20 OR PA.ID_APODOXHS BETWEEN 103 AND 106))
                GROUP BY KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, K.DESCR, PA.ID_APODOXHS, K.ID_KRATISI) AS A ON PD.ID_EMP = A.ID_EMP AND PD.XRISI = A.XRISI AND PD.ID_PERIODOS = A.ID_PERIODOS
            WHERE 
                ISNULL(A.PERC_ERGAZ, 0) > 0 AND 
                ISNULL(A.PERC_ERGOD, 0) > 0 AND 
                PD.ID_CMP IN(@pCompanyId)
            ORDER BY O.DESCR
            ";

        public static string InsurancePackagesAll => @"
            SELECT DISTINCT 
	            0 AS Id
	            , O.DESCR AS Description
            	, CAST(ISNULL(A.PERC_ERGAZ, 0) AS DECIMAL(18,4)) AS Employee
            	, CAST(ISNULL(A.PERC_ERGOD, 0) AS DECIMAL(18,4)) AS Employer
            FROM            
	            PERIODOI_DATA AS PD INNER JOIN
	            CMP AS C ON PD.ID_CMP = C.ID_CMP INNER JOIN
	            EMPLOYEE AS E ON PD.ID_EMP = E.ID_EMP INNER JOIN
	            OMADES AS O ON PD.ID_OMADA = O.ID_OMADA LEFT OUTER JOIN
                (SELECT KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, SUM(ISNULL(PK.POSO_ERGAZ, 0)) AS ERGAZ_POSO, SUM(ISNULL(PK.POSO_ERGOD, 0)) AS ERGOD_POSO, 
		            SUM(ISNULL(CASE WHEN ISNULL(PA.FMY_TYPE, 0) = 0 THEN PA.FMY ELSE PA.FMY_SINEK END, 0)) AS FMY, SUM(ISNULL(PA.M_APODOXES, 0)) AS M_APODOXES, SUM(ISNULL(PK.SUM_OAED_EPID, 0)) 
		            AS sum_oaed_epid, K.DESCR AS KRATISI, 5 AS ID_APODOXHS, K.ID_KRATISI, SUM(ISNULL(PK.MIKTA_KRAT, 0)) AS MIKTA_KRAT, MAX(PK.CALC_PERC_ERGAZ) AS PERC_ERGAZ, MAX(PK.CALC_PERC_ERGOD) AS PERC_ERGOD
                FROM PERIODOS_APOD AS PA LEFT OUTER JOIN
		            PER_KRATISEIS AS PK ON PA.ID_PERIODOS_APOD = PK.ID_PERIODOS_APOD LEFT OUTER JOIN
		            KRAT_TAMEIA AS KT ON PK.ID_KRATISI = KT.ID_KRATISI AND PK.ID_TAMEIO = KT.ID_TAMEIO LEFT OUTER JOIN
		            KRATISEIS AS K ON KT.ID_KRATISI = K.ID_KRATISI
	            WHERE
		            (PA.ID_APODOXHS BETWEEN 5 AND 20) OR
		            (PA.ID_APODOXHS BETWEEN 103 AND 106)
                GROUP BY KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, K.DESCR, K.ID_KRATISI
                UNION ALL
                SELECT KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, SUM(ISNULL(PK.POSO_ERGAZ, 0)) AS ERGAZ_POSO, SUM(ISNULL(PK.POSO_ERGOD, 0)) AS ERGOD_POSO, 
		            SUM(ISNULL(CASE WHEN ISNULL(PA.FMY_TYPE, 0) = 0 THEN PA.FMY ELSE PA.FMY_SINEK END, 0)) AS FMY, SUM(ISNULL(PA.M_APODOXES, 0)) AS M_APODOXES, 
		            SUM(ISNULL(PK.SUM_OAED_EPID, 0)) AS sum_oaed_epid, K.DESCR AS KRATISI, CASE WHEN PA.ID_PERIODOS IN (16, 24) THEN 24 WHEN PA.ID_PERIODOS = 17 THEN 25 ELSE 1 END AS ID_APODOXHS, K.ID_KRATISI, 
		            SUM(ISNULL(PK.MIKTA_KRAT, 0)) AS MIKTA_KRAT, MAX(PK.CALC_PERC_ERGAZ) AS PERC_ERGAZ, MAX(PK.CALC_PERC_ERGOD) AS PERC_ERGOD
	            FROM PERIODOS_APOD AS PA LEFT OUTER JOIN
		            PER_KRATISEIS AS PK ON PA.ID_PERIODOS_APOD = PK.ID_PERIODOS_APOD LEFT OUTER JOIN
		            KRAT_TAMEIA AS KT ON PK.ID_KRATISI = KT.ID_KRATISI AND PK.ID_TAMEIO = KT.ID_TAMEIO LEFT OUTER JOIN
		            KRATISEIS AS K ON KT.ID_KRATISI = K.ID_KRATISI
                WHERE (PA.ID_APODOXHS IN (1, 21, 22, 23, 27, 24, 25))
                GROUP BY KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, K.DESCR, K.ID_KRATISI, CASE WHEN PA.ID_PERIODOS IN (16, 24) THEN 24 WHEN PA.ID_PERIODOS = 17 THEN 25 ELSE 1 END
                UNION ALL
                SELECT KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, SUM(ISNULL(PK.POSO_ERGAZ, 0)) AS ERGAZ_POSO, SUM(ISNULL(PK.POSO_ERGOD, 0)) AS ERGOD_POSO, 
		            SUM(ISNULL(CASE WHEN ISNULL(PA.FMY_TYPE, 0) = 0 THEN PA.FMY ELSE PA.FMY_SINEK END, 0)) AS FMY, SUM(ISNULL(PA.M_APODOXES, 0)) AS M_APODOXES, SUM(ISNULL(PK.SUM_OAED_EPID, 0)) 
		            AS sum_oaed_epid, K.DESCR AS KRATISI, 26 AS ID_APODOXHS, K.ID_KRATISI, SUM(ISNULL(PK.MIKTA_KRAT, 0)) AS MIKTA_KRAT, MAX(PK.CALC_PERC_ERGAZ) AS PERC_ERGAZ, MAX(PK.CALC_PERC_ERGOD) AS PERC_ERGOD
                FROM PERIODOS_APOD AS PA LEFT OUTER JOIN
		            PER_KRATISEIS AS PK ON PA.ID_PERIODOS_APOD = PK.ID_PERIODOS_APOD LEFT OUTER JOIN
		            KRAT_TAMEIA AS KT ON PK.ID_KRATISI = KT.ID_KRATISI AND PK.ID_TAMEIO = KT.ID_TAMEIO LEFT OUTER JOIN
		            KRATISEIS AS K ON KT.ID_KRATISI = K.ID_KRATISI
                WHERE (PA.ID_APODOXHS IN (26))
                GROUP BY KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, K.DESCR, K.ID_KRATISI
                UNION ALL
                SELECT KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, SUM(ISNULL(PK.POSO_ERGAZ, 0)) AS ERGAZ_POSO, SUM(ISNULL(PK.POSO_ERGOD, 0)) AS ERGOD_POSO, 
		            SUM(ISNULL(CASE WHEN ISNULL(PA.FMY_TYPE, 0) = 0 THEN PA.FMY ELSE PA.FMY_SINEK END, 0)) AS FMY, SUM(ISNULL(PA.M_APODOXES, 0)) AS M_APODOXES, SUM(ISNULL(PK.SUM_OAED_EPID, 0)) AS sum_oaed_epid, 
		            K.DESCR AS KRATISI, 47 AS ID_APODOXHS, K.ID_KRATISI, SUM(ISNULL(PK.MIKTA_KRAT, 0)) AS MIKTA_KRAT, MAX(PK.CALC_PERC_ERGAZ) AS PERC_ERGAZ, MAX(PK.CALC_PERC_ERGOD) AS PERC_ERGOD
                FROM PERIODOS_APOD AS PA LEFT OUTER JOIN
		            PER_KRATISEIS AS PK ON PA.ID_PERIODOS_APOD = PK.ID_PERIODOS_APOD LEFT OUTER JOIN
		            KRAT_TAMEIA AS KT ON PK.ID_KRATISI = KT.ID_KRATISI AND PK.ID_TAMEIO = KT.ID_TAMEIO LEFT OUTER JOIN
		            KRATISEIS AS K ON KT.ID_KRATISI = K.ID_KRATISI
                WHERE (PA.ID_APODOXHS IN (47, 49, 50))
                GROUP BY KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, K.DESCR, K.ID_KRATISI
                UNION ALL
                SELECT KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, SUM(ISNULL(PK.POSO_ERGAZ, 0)) AS ERGAZ_POSO, SUM(ISNULL(PK.POSO_ERGOD, 0)) AS ERGOD_POSO, 
		            SUM(ISNULL(CASE WHEN ISNULL(PA.FMY_TYPE, 0) = 0 THEN PA.FMY ELSE PA.FMY_SINEK END, 0)) AS FMY, SUM(ISNULL(PA.M_APODOXES, 0)) AS M_APODOXES, SUM(ISNULL(PK.SUM_OAED_EPID, 0)) 
		            AS sum_oaed_epid, K.DESCR AS KRATISI, 2 AS ID_APODOXHS, K.ID_KRATISI, SUM(ISNULL(PK.MIKTA_KRAT, 0)) AS MIKTA_KRAT, MAX(PK.CALC_PERC_ERGAZ) AS PERC_ERGAZ, MAX(PK.CALC_PERC_ERGOD) AS PERC_ERGOD
                FROM PERIODOS_APOD AS PA LEFT OUTER JOIN
		            PER_KRATISEIS AS PK ON PA.ID_PERIODOS_APOD = PK.ID_PERIODOS_APOD LEFT OUTER JOIN
		            KRAT_TAMEIA AS KT ON PK.ID_KRATISI = KT.ID_KRATISI AND PK.ID_TAMEIO = KT.ID_TAMEIO LEFT OUTER JOIN
		            KRATISEIS AS K ON KT.ID_KRATISI = K.ID_KRATISI
                WHERE (PA.ID_APODOXHS BETWEEN 2 AND 4)
                GROUP BY KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, K.DESCR, K.ID_KRATISI
                UNION ALL
                SELECT KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, SUM(ISNULL(PK.POSO_ERGAZ, 0)) AS ERGAZ_POSO, SUM(ISNULL(PK.POSO_ERGOD, 0)) AS ERGOD_POSO, 
		            SUM(ISNULL(CASE WHEN ISNULL(PA.FMY_TYPE, 0) = 0 THEN PA.FMY ELSE PA.FMY_SINEK END, 0)) AS FMY, SUM(ISNULL(PA.M_APODOXES, 0)) AS M_APODOXES, SUM(ISNULL(PK.SUM_OAED_EPID, 0)) 
		            AS sum_oaed_epid, K.DESCR AS KRATISI, PA.ID_APODOXHS, K.ID_KRATISI, SUM(ISNULL(PK.MIKTA_KRAT, 0)) AS MIKTA_KRAT, MAX(PK.CALC_PERC_ERGAZ) AS PERC_ERGAZ, MAX(PK.CALC_PERC_ERGOD) AS PERC_ERGOD
                FROM PERIODOS_APOD AS PA LEFT OUTER JOIN
		            PER_KRATISEIS AS PK ON PA.ID_PERIODOS_APOD = PK.ID_PERIODOS_APOD LEFT OUTER JOIN
		            KRAT_TAMEIA AS KT ON PK.ID_KRATISI = KT.ID_KRATISI AND PK.ID_TAMEIO = KT.ID_TAMEIO LEFT OUTER JOIN
		            KRATISEIS AS K ON KT.ID_KRATISI = K.ID_KRATISI
                WHERE (NOT (PA.ID_APODOXHS BETWEEN 2 AND 4 OR
		            PA.ID_APODOXHS IN (47, 49, 50, 1, 21, 22, 23, 26, 27, 24, 25) OR PA.ID_APODOXHS BETWEEN 5 AND 20 OR PA.ID_APODOXHS BETWEEN 103 AND 106))
                GROUP BY KT.ID_TAMEIO, PA.ID_EMP, PA.XRISI, PA.ID_PERIODOS, K.DESCR, PA.ID_APODOXHS, K.ID_KRATISI) AS A ON PD.ID_EMP = A.ID_EMP AND PD.XRISI = A.XRISI AND PD.ID_PERIODOS = A.ID_PERIODOS
            WHERE 
                ISNULL(A.PERC_ERGAZ, 0) > 0 AND 
                ISNULL(A.PERC_ERGOD, 0) > 0
            ORDER BY O.DESCR
            ";

        /*
         SELECT
           DATEADD(yy, DATEDIFF(yy, 0, GETDATE()), 0) AS StartOfYear,
           DATEADD(yy, DATEDIFF(yy, 0, GETDATE()) + 1, -1) AS EndOfYear

           WHERE YEAR(A.[reimbursementDate]) = YEAR(GETDATE()) // Current year
         */
        public static string WorkerCatalog => @"
            SELECT EMPLOYEE.BRTHDATE AS BirthDate, EMPLOYEE.AM_KOIN_ASF AS Amka
                ,EMPLOYEE.ID_EMP AS EmployeeId
                ,EMPLOYEE.ACTIVE_CARD AS ActiveCard
                ,PERIODOI_DATA.ID_CMP AS CompanyId
                ,CMP.ISACTIVE AS CompanyIsActive 
                ,CMP.CMP_CALCDATE AS CompanyCalcDate
                ,case when exists (SELECT 1 FROM EMPLOYEE E WITH(NOLOCK)                                                                  
                    JOIN PERIODOI_DATA PD WITH(NOLOCK) On E.id_emp=PD.id_emp and PD.id_periodos=0 and PD.xrisi = 0         
                    WHERE (E.ID_EMP=EMPLOYEE.id_emp) AND                                                                   
                    (((((E.FRDATE IS NOT NULL) AND (E.FRDATE<=DATEADD(yy, DATEDIFF(yy, 0, GETDATE()) + 1, -1)))                                    
 	                OR                                                                                                      
                    ((E.FRDATE IS NULL) AND (IsNull(PD.IsActive, 0)=0)))	AND (IsNull(E.VAT, 0)<>0) AND                     
                    (NOT EXISTS (SELECT 1 FROM EMPLOYEE E_2 WITH(NOLOCK)                                                   
                    JOIN PERIODOI_DATA PD_2 On PD_2.id_emp=E_2.id_emp and PD_2.xrisi=0 and PD_2.id_periodos=0             
                    WHERE (E_2.id_emp<>E.id_emp) AND (E_2.VAT=E.VAT) and (PD_2.id_cmp=PD.id_cmp)                          
 			            And ((((E_2.FRDATE IS Not NULL) And ((E_2.FRDATE)>DATEADD(yy, DATEDIFF(yy, 0, GETDATE()) + 1, -1))) Or (E_2.FRDATE Is Null))   
                    And (E_2.HRDATE<=DATEADD(yy, DATEDIFF(yy, 0, GETDATE()) + 1, -1))) AND (IsNull(PD_2.IsActive, 0)=1))) OR ((IsNull(E.VAT, 0)=0)
                    AND (E.HRDATE<=DATEADD(yy, DATEDIFF(yy, 0, GETDATE()) + 1, -1)) AND  (((E.FRDATE Is Not Null) AND 
                    (E.FRDATE<=DATEADD(yy, DATEDIFF(yy, 0, GETDATE()) + 1, -1))) OR ((E.FRDATE Is Null) and (IsNull(PD.IsActive, 0)=0)))))))  
                             AND ISNULL(EMPLOYEE.NONPAYROLLCALCULATION, 0) in (0,2) THEN 1 ELSE 0 END AS IsInActive 
                ,EMPLOYEE.AM_IKA AS AmIka
                ,PERIODOI_DATA.SALARY AS Salary
                ,PERIODOI_DATA.SALARY_AGREED AS SalaryAgreed
                ,CASE WHEN PERIODOI_DATA.OAED_EPID = 0 THEN NULL ELSE EMPLOYEE.HOTEL_OAED_EPID_START END AS OaedEpidomaDate
                ,CMP.NAME + ' ' + ISNULL(CMP.FRSTNAME,'') AS CompanyName
                ,PERIODOI_DATA.EPIDOTHSH_ERGOT_PERCENT AS EpidotisiErgodPercent
                ,CASE WHEN MONTH(GETDATE())>MONTH(EMPLOYEE.BRTHDATE) THEN YEAR(GETDATE())-YEAR(EMPLOYEE.BRTHDATE)
                     WHEN MONTH(GETDATE())<MONTH(EMPLOYEE.BRTHDATE) THEN YEAR(GETDATE())-YEAR(EMPLOYEE.BRTHDATE)-1
                ELSE 
                CASE WHEN DAY(GETDATE())<DAY(EMPLOYEE.BRTHDATE) THEN YEAR(GETDATE())-YEAR(EMPLOYEE.BRTHDATE)-1
                     ELSE YEAR(GETDATE())-YEAR(EMPLOYEE.BRTHDATE)END END AS Birthday
                ,case when IsNull(periodoi_data.OAED_EPID,0)>0 then op.descr else '' end AS OaedEpidoma
                ,PERIODOI_DATA.CNDTDESCR AS CndtDescr
                ,SEPE_OAED.DESCR AS SepeOaedDesc
                ,SEPE_OAED.CODE AS SepeOaedCode
                ,EMPLOYEE.AM_KOIN_ASF AS AmKoinAsf
                ,CASE 
                WHEN PERIODOI_DATA.OAED_EPID = 0 THEN 'ΟΧΙ' 
                WHEN PERIODOI_DATA.OAED_EPID = 1 THEN 'ΝΑΙ'
                ELSE ' ' END AS OaedEpidotisi
                ,PERIODOI_DATA.ID_EID AS EidikotitaId
                ,PERIODOI_DATA.ID_KPK AS PackageId
                ,DN_EID.DESCR AS EidikotitaDesc
				,PERIODOI_DATA.COD_YPOKAT AS UpokCode
                ,EMP_TYPES.DESCR AS EmployeeType
                ,PERIODOI_DATA.ORES_ERGASIAS AS OresErgasias
                ,SPC.SPC AS EmployeeSpc
                ,case PERIODOI_DATA.EMP_KIND when 0 then 'ΕΜΜΙΣΘΟΣ'       
                                            when 1 then 'ΗΜΕΡΟΜΙΣΘΙΟΣ'   
                                            when 2 then 'ΩΡΟΜΙΣΘΙΟΣ' end 
                 AS EmployeeKind
                ,case when PERIODOI_DATA.ORISMENOU = 0 then (SELECT TOP 1 S.ST_DATE FROM EMP_SYMVASEIS_DATES S WITH(NOLOCK) WHERE S.ID_EMP=EMPLOYEE.ID_EMP AND S.[TYPE]=0
                   ORDER BY S.ST_DATE DESC, S.END_DATE DESC)  end                                           
                 AS Orismenou
                ,case when PERIODOI_DATA.ORISMENOU = 0 then (SELECT TOP 1 S.END_DATE FROM EMP_SYMVASEIS_DATES S WITH(NOLOCK) WHERE S.ID_EMP=EMPLOYEE.ID_EMP AND S.[TYPE]=0
                  ORDER BY S.ST_DATE DESC, S.END_DATE DESC) end  AS OrismenouExpire
                ,case PERIODOI_DATA.MERIKH_APASX when 0 then 'ΟΧΙ' when 1 then 'ΝΑΙ' end AS MerikiApasx
                ,PERIODOI_DATA.SPC_DESCR AS EmployeeSpcDesc
                ,case PERIODOI_DATA.MERIKH_PLIRES_ORARIO when 1 then 'ΝΑΙ' else 'ΟΧΙ' end AS PliresOrario
                ,PERIODOI_DATA.DAY_HOURS AS DayHours
                ,EMPLOYEE.sVAT AS Vat
                ,EMPLOYEE.SURNAME AS Surname
                ,EMPLOYEE.CODE AS EmployeeCode
                ,EMPLOYEE.NAME AS EmployeeName
                ,CASE EMPLOYEE.FR_REASON WHEN 0 then 'Οικειοθελής'
                WHEN 1 then 'Απόλυση'
                WHEN 2 then 'Συνταξιοδότηση'
                WHEN 3 then 'Λήξη Σύμβασης'
                WHEN 4 THEN 'Στράτευση'
                WHEN 5 THEN 'Μεταβολή Προσώπου Εργοδότη Σε'
                WHEN 6 THEN 'Λύση Δανεισμού'
                WHEN 7 THEN 'Δανεισμός Σε'
                WHEN 8 THEN 'Άλλος'
                WHEN 9 THEN 'Αλλαγή Εργασιακής Σχέσης'
                WHEN 10 THEN 'Οικειοθελής με 15 έτη προϋπηρεσία'
                WHEN 11 THEN 'Μεταφορά σε άλλη Εταιρεία'
                ELSE cast(null as varchar) END AS FrReason
                ,EMPLOYEE.HRDATE AS HrDate
                ,EMPLOYEE.FRDATE AS FrDate
			FROM EMPLOYEE 
			JOIN PERIODOI_DATA ON PERIODOI_DATA.ID_EMP=EMPLOYEE.ID_EMP AND PERIODOI_DATA.XRISI=0 AND PERIODOI_DATA.ID_PERIODOS=0
			JOIN CMP ON CMP.ID_CMP=PERIODOI_DATA.ID_CMP 
			LEFT JOIN CNDT ON CNDT.CNDTID=PERIODOI_DATA.CNDTID
			LEFT JOIN CNTR ON CNTR.CNTRID=CNDT.CNTRID
			LEFT JOIN SPC ON SPC.SPCID=CNDT.SPCID
			LEFT JOIN OAED_CATEGORY OC ON OC.ID=PERIODOI_DATA.OAED_EMP_TYPE
			LEFT JOIN OAED_PROGRAM OP ON OP.ID=OC.ID_GROUP
			LEFT JOIN DN_EID ON PERIODOI_DATA.ID_EID=DN_EID.ID_EID
			LEFT JOIN EMP_TYPES ON EMP_TYPES.EMP_TYPE=PERIODOI_DATA.EMP_TYPE
			LEFT JOIN SEPE_OAED ON PERIODOI_DATA.ID_SEPE_OAED=SEPE_OAED.ID_SEPE_OAED
				 LEFT JOIN (SELECT COUNT(*) AS COUNT_VATS,PD.ID_CMP,E.VAT,PD.XRISI,PD.ID_PERIODOS  
							FROM EMPLOYEE E                                                        
							   JOIN PERIODOI_DATA PD ON PD.ID_EMP=E.ID_EMP                            
							   WHERE E.VAT IS NOT NULL AND E.ACTIVE_CARD<>1                           
							   AND PD.XRISI=0 AND PD.ID_PERIODOS=0                                    
							   GROUP BY                                                               
							   PD.ID_CMP,E.VAT,PD.XRISI,PD.ID_PERIODOS                                
							   ) V_OTHER_VAT ON PERIODOI_DATA.ID_CMP = V_OTHER_VAT.ID_CMP AND EMPLOYEE.VAT = V_OTHER_VAT.VAT 
					  AND PERIODOI_DATA.XRISI = V_OTHER_VAT.XRISI AND PERIODOI_DATA.ID_PERIODOS = V_OTHER_VAT.ID_PERIODOS    
			WHERE 1=1 AND 1=1 AND 1=1  AND 1=1 AND  (PERIODOI_DATA.EMP_TYPE IS NULL OR (NOT ( (PERIODOI_DATA.EMP_TYPE = 6 ) 
			)))  AND ((EMPLOYEE.ACTIVE_CARD=1 AND IsNull(employee.vat,0)<>0 and 
			  exists (select 1 from employee e WITH(NOLOCK) 
					  join periodoi_data pd on pd.xrisi=0 and pd.id_periodos=0  and pd.id_emp=e.id_emp 
					  where pd.xrisi = periodoi_data.xrisi and pd.ID_PERIODOS = periodoi_data.ID_PERIODOS and e.vat is not null and 
					  e.vat=employee.vat and pd.id_cmp=periodoi_data.ID_cmp AND     ( YEAR(E.FRDATE) >= YEAR(GETDATE()) OR E.FRDATE IS NULL)      
                        AND YEAR(E.HRDATE) <= YEAR(GETDATE())) )  or (IsNull(employee.vat,0)=0 and     ( YEAR(employee.FRDATE) >= YEAR(GETDATE()) OR employee.FRDATE IS NULL)      
                        AND YEAR(employee.HRDATE) <= YEAR(GETDATE())) ) AND PERIODOI_DATA.ID_CMP =@pCompanyId and ((EMPLOYEE.ID_EMP > 0) or ((EMPLOYEE.ID_EMP < 0) and (isnull(EMPLOYEE.IsBDGRec,0)=1))) 
            ";
    }
}
